var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn, CreateDateColumn, UpdateDateColumn, } from 'typeorm';
let Role = (() => {
    let _classDecorators = [Entity('roles')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _name_decorators;
    let _name_initializers = [];
    let _name_extraInitializers = [];
    let _description_decorators;
    let _description_initializers = [];
    let _description_extraInitializers = [];
    let _isSystem_decorators;
    let _isSystem_initializers = [];
    let _isSystem_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    var Role = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.name = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _name_initializers, void 0));
            this.description = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _description_initializers, void 0));
            this.isSystem = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _isSystem_initializers, void 0));
            this.createdAt = (__runInitializers(this, _isSystem_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            __runInitializers(this, _createdAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "Role");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _name_decorators = [Column({ unique: true })];
        _description_decorators = [Column({ nullable: true, type: 'text' })];
        _isSystem_decorators = [Column({ name: 'is_system', default: false })];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: obj => "name" in obj, get: obj => obj.name, set: (obj, value) => { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
        __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: obj => "description" in obj, get: obj => obj.description, set: (obj, value) => { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
        __esDecorate(null, null, _isSystem_decorators, { kind: "field", name: "isSystem", static: false, private: false, access: { has: obj => "isSystem" in obj, get: obj => obj.isSystem, set: (obj, value) => { obj.isSystem = value; } }, metadata: _metadata }, _isSystem_initializers, _isSystem_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Role = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Role = _classThis;
})();
export { Role };
let Branch = (() => {
    let _classDecorators = [Entity('branches')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _name_decorators;
    let _name_initializers = [];
    let _name_extraInitializers = [];
    let _code_decorators;
    let _code_initializers = [];
    let _code_extraInitializers = [];
    let _address_decorators;
    let _address_initializers = [];
    let _address_extraInitializers = [];
    let _city_decorators;
    let _city_initializers = [];
    let _city_extraInitializers = [];
    let _state_decorators;
    let _state_initializers = [];
    let _state_extraInitializers = [];
    let _pincode_decorators;
    let _pincode_initializers = [];
    let _pincode_extraInitializers = [];
    let _phone_decorators;
    let _phone_initializers = [];
    let _phone_extraInitializers = [];
    let _whatsapp_decorators;
    let _whatsapp_initializers = [];
    let _whatsapp_extraInitializers = [];
    let _email_decorators;
    let _email_initializers = [];
    let _email_extraInitializers = [];
    let _instagram_decorators;
    let _instagram_initializers = [];
    let _instagram_extraInitializers = [];
    let _workingHours_decorators;
    let _workingHours_initializers = [];
    let _workingHours_extraInitializers = [];
    let _mapUrl_decorators;
    let _mapUrl_initializers = [];
    let _mapUrl_extraInitializers = [];
    let _sortOrder_decorators;
    let _sortOrder_initializers = [];
    let _sortOrder_extraInitializers = [];
    let _gstin_decorators;
    let _gstin_initializers = [];
    let _gstin_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    var Branch = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.name = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _name_initializers, void 0));
            this.code = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _code_initializers, void 0));
            this.address = (__runInitializers(this, _code_extraInitializers), __runInitializers(this, _address_initializers, void 0));
            this.city = (__runInitializers(this, _address_extraInitializers), __runInitializers(this, _city_initializers, void 0));
            this.state = (__runInitializers(this, _city_extraInitializers), __runInitializers(this, _state_initializers, void 0));
            this.pincode = (__runInitializers(this, _state_extraInitializers), __runInitializers(this, _pincode_initializers, void 0));
            this.phone = (__runInitializers(this, _pincode_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
            this.whatsapp = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _whatsapp_initializers, void 0));
            this.email = (__runInitializers(this, _whatsapp_extraInitializers), __runInitializers(this, _email_initializers, void 0));
            this.instagram = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _instagram_initializers, void 0));
            this.workingHours = (__runInitializers(this, _instagram_extraInitializers), __runInitializers(this, _workingHours_initializers, void 0));
            this.mapUrl = (__runInitializers(this, _workingHours_extraInitializers), __runInitializers(this, _mapUrl_initializers, void 0));
            this.sortOrder = (__runInitializers(this, _mapUrl_extraInitializers), __runInitializers(this, _sortOrder_initializers, void 0));
            this.gstin = (__runInitializers(this, _sortOrder_extraInitializers), __runInitializers(this, _gstin_initializers, void 0));
            this.isActive = (__runInitializers(this, _gstin_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.createdAt = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            __runInitializers(this, _createdAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "Branch");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _name_decorators = [Column()];
        _code_decorators = [Column({ unique: true })];
        _address_decorators = [Column({ nullable: true, type: 'text' })];
        _city_decorators = [Column({ nullable: true, type: 'varchar' })];
        _state_decorators = [Column({ nullable: true, type: 'varchar' })];
        _pincode_decorators = [Column({ nullable: true, type: 'varchar', length: 10 })];
        _phone_decorators = [Column({ nullable: true, type: 'varchar', length: 15 })];
        _whatsapp_decorators = [Column({ nullable: true, type: 'varchar' })];
        _email_decorators = [Column({ nullable: true, type: 'varchar' })];
        _instagram_decorators = [Column({ nullable: true, type: 'varchar', length: 200 })];
        _workingHours_decorators = [Column({ name: 'working_hours', nullable: true, type: 'varchar', length: 100 })];
        _mapUrl_decorators = [Column({ name: 'map_url', nullable: true, type: 'varchar' })];
        _sortOrder_decorators = [Column({ name: 'sort_order', nullable: true, type: 'int', default: 0 })];
        _gstin_decorators = [Column({ nullable: true, type: 'varchar' })];
        _isActive_decorators = [Column({ name: 'is_active', default: true })];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: obj => "name" in obj, get: obj => obj.name, set: (obj, value) => { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
        __esDecorate(null, null, _code_decorators, { kind: "field", name: "code", static: false, private: false, access: { has: obj => "code" in obj, get: obj => obj.code, set: (obj, value) => { obj.code = value; } }, metadata: _metadata }, _code_initializers, _code_extraInitializers);
        __esDecorate(null, null, _address_decorators, { kind: "field", name: "address", static: false, private: false, access: { has: obj => "address" in obj, get: obj => obj.address, set: (obj, value) => { obj.address = value; } }, metadata: _metadata }, _address_initializers, _address_extraInitializers);
        __esDecorate(null, null, _city_decorators, { kind: "field", name: "city", static: false, private: false, access: { has: obj => "city" in obj, get: obj => obj.city, set: (obj, value) => { obj.city = value; } }, metadata: _metadata }, _city_initializers, _city_extraInitializers);
        __esDecorate(null, null, _state_decorators, { kind: "field", name: "state", static: false, private: false, access: { has: obj => "state" in obj, get: obj => obj.state, set: (obj, value) => { obj.state = value; } }, metadata: _metadata }, _state_initializers, _state_extraInitializers);
        __esDecorate(null, null, _pincode_decorators, { kind: "field", name: "pincode", static: false, private: false, access: { has: obj => "pincode" in obj, get: obj => obj.pincode, set: (obj, value) => { obj.pincode = value; } }, metadata: _metadata }, _pincode_initializers, _pincode_extraInitializers);
        __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: obj => "phone" in obj, get: obj => obj.phone, set: (obj, value) => { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
        __esDecorate(null, null, _whatsapp_decorators, { kind: "field", name: "whatsapp", static: false, private: false, access: { has: obj => "whatsapp" in obj, get: obj => obj.whatsapp, set: (obj, value) => { obj.whatsapp = value; } }, metadata: _metadata }, _whatsapp_initializers, _whatsapp_extraInitializers);
        __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: obj => "email" in obj, get: obj => obj.email, set: (obj, value) => { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
        __esDecorate(null, null, _instagram_decorators, { kind: "field", name: "instagram", static: false, private: false, access: { has: obj => "instagram" in obj, get: obj => obj.instagram, set: (obj, value) => { obj.instagram = value; } }, metadata: _metadata }, _instagram_initializers, _instagram_extraInitializers);
        __esDecorate(null, null, _workingHours_decorators, { kind: "field", name: "workingHours", static: false, private: false, access: { has: obj => "workingHours" in obj, get: obj => obj.workingHours, set: (obj, value) => { obj.workingHours = value; } }, metadata: _metadata }, _workingHours_initializers, _workingHours_extraInitializers);
        __esDecorate(null, null, _mapUrl_decorators, { kind: "field", name: "mapUrl", static: false, private: false, access: { has: obj => "mapUrl" in obj, get: obj => obj.mapUrl, set: (obj, value) => { obj.mapUrl = value; } }, metadata: _metadata }, _mapUrl_initializers, _mapUrl_extraInitializers);
        __esDecorate(null, null, _sortOrder_decorators, { kind: "field", name: "sortOrder", static: false, private: false, access: { has: obj => "sortOrder" in obj, get: obj => obj.sortOrder, set: (obj, value) => { obj.sortOrder = value; } }, metadata: _metadata }, _sortOrder_initializers, _sortOrder_extraInitializers);
        __esDecorate(null, null, _gstin_decorators, { kind: "field", name: "gstin", static: false, private: false, access: { has: obj => "gstin" in obj, get: obj => obj.gstin, set: (obj, value) => { obj.gstin = value; } }, metadata: _metadata }, _gstin_initializers, _gstin_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Branch = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Branch = _classThis;
})();
export { Branch };
let User = (() => {
    let _classDecorators = [Entity('users')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _email_decorators;
    let _email_initializers = [];
    let _email_extraInitializers = [];
    let _phone_decorators;
    let _phone_initializers = [];
    let _phone_extraInitializers = [];
    let _passwordHash_decorators;
    let _passwordHash_initializers = [];
    let _passwordHash_extraInitializers = [];
    let _firstName_decorators;
    let _firstName_initializers = [];
    let _firstName_extraInitializers = [];
    let _lastName_decorators;
    let _lastName_initializers = [];
    let _lastName_extraInitializers = [];
    let _role_decorators;
    let _role_initializers = [];
    let _role_extraInitializers = [];
    let _roleId_decorators;
    let _roleId_initializers = [];
    let _roleId_extraInitializers = [];
    let _branch_decorators;
    let _branch_initializers = [];
    let _branch_extraInitializers = [];
    let _branchId_decorators;
    let _branchId_initializers = [];
    let _branchId_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    let _avatarUrl_decorators;
    let _avatarUrl_initializers = [];
    let _avatarUrl_extraInitializers = [];
    let _walletBalance_decorators;
    let _walletBalance_initializers = [];
    let _walletBalance_extraInitializers = [];
    let _emailEnabled_decorators;
    let _emailEnabled_initializers = [];
    let _emailEnabled_extraInitializers = [];
    let _smsEnabled_decorators;
    let _smsEnabled_initializers = [];
    let _smsEnabled_extraInitializers = [];
    let _whatsappEnabled_decorators;
    let _whatsappEnabled_initializers = [];
    let _whatsappEnabled_extraInitializers = [];
    let _lastLoginAt_decorators;
    let _lastLoginAt_initializers = [];
    let _lastLoginAt_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var User = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.email = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _email_initializers, void 0));
            this.phone = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
            this.passwordHash = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _passwordHash_initializers, void 0));
            this.firstName = (__runInitializers(this, _passwordHash_extraInitializers), __runInitializers(this, _firstName_initializers, void 0));
            this.lastName = (__runInitializers(this, _firstName_extraInitializers), __runInitializers(this, _lastName_initializers, void 0));
            this.role = (__runInitializers(this, _lastName_extraInitializers), __runInitializers(this, _role_initializers, void 0));
            this.roleId = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _roleId_initializers, void 0));
            this.branch = (__runInitializers(this, _roleId_extraInitializers), __runInitializers(this, _branch_initializers, void 0));
            this.branchId = (__runInitializers(this, _branch_extraInitializers), __runInitializers(this, _branchId_initializers, void 0));
            this.isActive = (__runInitializers(this, _branchId_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.avatarUrl = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _avatarUrl_initializers, void 0));
            this.walletBalance = (__runInitializers(this, _avatarUrl_extraInitializers), __runInitializers(this, _walletBalance_initializers, void 0));
            this.emailEnabled = (__runInitializers(this, _walletBalance_extraInitializers), __runInitializers(this, _emailEnabled_initializers, void 0));
            this.smsEnabled = (__runInitializers(this, _emailEnabled_extraInitializers), __runInitializers(this, _smsEnabled_initializers, void 0));
            this.whatsappEnabled = (__runInitializers(this, _smsEnabled_extraInitializers), __runInitializers(this, _whatsappEnabled_initializers, void 0));
            this.lastLoginAt = (__runInitializers(this, _whatsappEnabled_extraInitializers), __runInitializers(this, _lastLoginAt_initializers, void 0));
            this.createdAt = (__runInitializers(this, _lastLoginAt_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "User");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _email_decorators = [Column({ unique: true, nullable: true, type: 'varchar' })];
        _phone_decorators = [Column({ unique: true })];
        _passwordHash_decorators = [Column({ name: 'password_hash' })];
        _firstName_decorators = [Column({ name: 'first_name' })];
        _lastName_decorators = [Column({ name: 'last_name', nullable: true, type: 'varchar' })];
        _role_decorators = [ManyToOne(() => Role, { eager: false, nullable: true }), JoinColumn({ name: 'role_id' })];
        _roleId_decorators = [Column({ name: 'role_id', nullable: true, type: 'varchar' })];
        _branch_decorators = [ManyToOne(() => Branch, { eager: false, nullable: true }), JoinColumn({ name: 'branch_id' })];
        _branchId_decorators = [Column({ name: 'branch_id', nullable: true, type: 'varchar' })];
        _isActive_decorators = [Column({ name: 'is_active', default: true })];
        _avatarUrl_decorators = [Column({ name: 'avatar_url', nullable: true, type: 'varchar' })];
        _walletBalance_decorators = [Column({ name: 'wallet_balance', default: 0, type: 'decimal', precision: 12, scale: 2 })];
        _emailEnabled_decorators = [Column({ name: 'email_enabled', default: true })];
        _smsEnabled_decorators = [Column({ name: 'sms_enabled', default: true })];
        _whatsappEnabled_decorators = [Column({ name: 'whatsapp_enabled', default: true })];
        _lastLoginAt_decorators = [Column({ name: 'last_login_at', nullable: true, type: 'timestamptz' })];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        _updatedAt_decorators = [UpdateDateColumn({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: obj => "email" in obj, get: obj => obj.email, set: (obj, value) => { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
        __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: obj => "phone" in obj, get: obj => obj.phone, set: (obj, value) => { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
        __esDecorate(null, null, _passwordHash_decorators, { kind: "field", name: "passwordHash", static: false, private: false, access: { has: obj => "passwordHash" in obj, get: obj => obj.passwordHash, set: (obj, value) => { obj.passwordHash = value; } }, metadata: _metadata }, _passwordHash_initializers, _passwordHash_extraInitializers);
        __esDecorate(null, null, _firstName_decorators, { kind: "field", name: "firstName", static: false, private: false, access: { has: obj => "firstName" in obj, get: obj => obj.firstName, set: (obj, value) => { obj.firstName = value; } }, metadata: _metadata }, _firstName_initializers, _firstName_extraInitializers);
        __esDecorate(null, null, _lastName_decorators, { kind: "field", name: "lastName", static: false, private: false, access: { has: obj => "lastName" in obj, get: obj => obj.lastName, set: (obj, value) => { obj.lastName = value; } }, metadata: _metadata }, _lastName_initializers, _lastName_extraInitializers);
        __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: obj => "role" in obj, get: obj => obj.role, set: (obj, value) => { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
        __esDecorate(null, null, _roleId_decorators, { kind: "field", name: "roleId", static: false, private: false, access: { has: obj => "roleId" in obj, get: obj => obj.roleId, set: (obj, value) => { obj.roleId = value; } }, metadata: _metadata }, _roleId_initializers, _roleId_extraInitializers);
        __esDecorate(null, null, _branch_decorators, { kind: "field", name: "branch", static: false, private: false, access: { has: obj => "branch" in obj, get: obj => obj.branch, set: (obj, value) => { obj.branch = value; } }, metadata: _metadata }, _branch_initializers, _branch_extraInitializers);
        __esDecorate(null, null, _branchId_decorators, { kind: "field", name: "branchId", static: false, private: false, access: { has: obj => "branchId" in obj, get: obj => obj.branchId, set: (obj, value) => { obj.branchId = value; } }, metadata: _metadata }, _branchId_initializers, _branchId_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _avatarUrl_decorators, { kind: "field", name: "avatarUrl", static: false, private: false, access: { has: obj => "avatarUrl" in obj, get: obj => obj.avatarUrl, set: (obj, value) => { obj.avatarUrl = value; } }, metadata: _metadata }, _avatarUrl_initializers, _avatarUrl_extraInitializers);
        __esDecorate(null, null, _walletBalance_decorators, { kind: "field", name: "walletBalance", static: false, private: false, access: { has: obj => "walletBalance" in obj, get: obj => obj.walletBalance, set: (obj, value) => { obj.walletBalance = value; } }, metadata: _metadata }, _walletBalance_initializers, _walletBalance_extraInitializers);
        __esDecorate(null, null, _emailEnabled_decorators, { kind: "field", name: "emailEnabled", static: false, private: false, access: { has: obj => "emailEnabled" in obj, get: obj => obj.emailEnabled, set: (obj, value) => { obj.emailEnabled = value; } }, metadata: _metadata }, _emailEnabled_initializers, _emailEnabled_extraInitializers);
        __esDecorate(null, null, _smsEnabled_decorators, { kind: "field", name: "smsEnabled", static: false, private: false, access: { has: obj => "smsEnabled" in obj, get: obj => obj.smsEnabled, set: (obj, value) => { obj.smsEnabled = value; } }, metadata: _metadata }, _smsEnabled_initializers, _smsEnabled_extraInitializers);
        __esDecorate(null, null, _whatsappEnabled_decorators, { kind: "field", name: "whatsappEnabled", static: false, private: false, access: { has: obj => "whatsappEnabled" in obj, get: obj => obj.whatsappEnabled, set: (obj, value) => { obj.whatsappEnabled = value; } }, metadata: _metadata }, _whatsappEnabled_initializers, _whatsappEnabled_extraInitializers);
        __esDecorate(null, null, _lastLoginAt_decorators, { kind: "field", name: "lastLoginAt", static: false, private: false, access: { has: obj => "lastLoginAt" in obj, get: obj => obj.lastLoginAt, set: (obj, value) => { obj.lastLoginAt = value; } }, metadata: _metadata }, _lastLoginAt_initializers, _lastLoginAt_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        User = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return User = _classThis;
})();
export { User };
//# sourceMappingURL=user.entity.js.map