import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react';
export function TablePagination({ table, total }) {
    const page = table.getState().pagination.pageIndex + 1;
    const pageSize = table.getState().pagination.pageSize;
    const start = (page - 1) * pageSize + 1;
    const end = Math.min(page * pageSize, total);
    return (_jsxs("div", { className: "flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-sm text-surface-500", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { children: ["Showing ", _jsx("span", { className: "font-medium text-surface-900", children: start }), "\u2013", _jsx("span", { className: "font-medium text-surface-900", children: end }), " of", ' ', _jsx("span", { className: "font-medium text-surface-900", children: total })] }), _jsxs("select", { value: pageSize, onChange: (e) => {
                            table.setPageSize(Number(e.target.value));
                        }, className: "select text-xs py-1.5 px-2 rounded-lg w-auto", children: [_jsx("option", { value: 10, children: "10 / page" }), _jsx("option", { value: 20, children: "20 / page" }), _jsx("option", { value: 50, children: "50 / page" }), _jsx("option", { value: 100, children: "100 / page" })] })] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("button", { onClick: () => table.setPageIndex(0), disabled: !table.getCanPreviousPage(), className: "p-1.5 rounded-lg text-surface-400 hover:bg-surface-100 hover:text-surface-700 disabled:opacity-30 disabled:cursor-not-allowed transition-all", children: _jsx(ChevronsLeft, { className: "w-4 h-4" }) }), _jsx("button", { onClick: () => table.previousPage(), disabled: !table.getCanPreviousPage(), className: "p-1.5 rounded-lg text-surface-400 hover:bg-surface-100 hover:text-surface-700 disabled:opacity-30 disabled:cursor-not-allowed transition-all", children: _jsx(ChevronLeft, { className: "w-4 h-4" }) }), _jsxs("span", { className: "px-3 text-xs text-surface-500", children: ["Page ", _jsx("span", { className: "font-semibold text-surface-900", children: page }), " of", ' ', _jsx("span", { className: "font-semibold text-surface-900", children: table.getPageCount() })] }), _jsx("button", { onClick: () => table.nextPage(), disabled: !table.getCanNextPage(), className: "p-1.5 rounded-lg text-surface-400 hover:bg-surface-100 hover:text-surface-700 disabled:opacity-30 disabled:cursor-not-allowed transition-all", children: _jsx(ChevronRight, { className: "w-4 h-4" }) }), _jsx("button", { onClick: () => table.setPageIndex(table.getPageCount() - 1), disabled: !table.getCanNextPage(), className: "p-1.5 rounded-lg text-surface-400 hover:bg-surface-100 hover:text-surface-700 disabled:opacity-30 disabled:cursor-not-allowed transition-all", children: _jsx(ChevronsRight, { className: "w-4 h-4" }) })] })] }));
}
//# sourceMappingURL=TablePagination.js.map