var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn, CreateDateColumn, UpdateDateColumn, } from 'typeorm';
import { Branch, User } from '../../auth/entities/user.entity';
let Client = (() => {
    let _classDecorators = [Entity('clients')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _firstName_decorators;
    let _firstName_initializers = [];
    let _firstName_extraInitializers = [];
    let _lastName_decorators;
    let _lastName_initializers = [];
    let _lastName_extraInitializers = [];
    let _phone_decorators;
    let _phone_initializers = [];
    let _phone_extraInitializers = [];
    let _alternatePhone_decorators;
    let _alternatePhone_initializers = [];
    let _alternatePhone_extraInitializers = [];
    let _email_decorators;
    let _email_initializers = [];
    let _email_extraInitializers = [];
    let _gender_decorators;
    let _gender_initializers = [];
    let _gender_extraInitializers = [];
    let _dateOfBirth_decorators;
    let _dateOfBirth_initializers = [];
    let _dateOfBirth_extraInitializers = [];
    let _address_decorators;
    let _address_initializers = [];
    let _address_extraInitializers = [];
    let _city_decorators;
    let _city_initializers = [];
    let _city_extraInitializers = [];
    let _district_decorators;
    let _district_initializers = [];
    let _district_extraInitializers = [];
    let _state_decorators;
    let _state_initializers = [];
    let _state_extraInitializers = [];
    let _pincode_decorators;
    let _pincode_initializers = [];
    let _pincode_extraInitializers = [];
    let _gstin_decorators;
    let _gstin_initializers = [];
    let _gstin_extraInitializers = [];
    let _idProofType_decorators;
    let _idProofType_initializers = [];
    let _idProofType_extraInitializers = [];
    let _idProofNumber_decorators;
    let _idProofNumber_initializers = [];
    let _idProofNumber_extraInitializers = [];
    let _ekycStatus_decorators;
    let _ekycStatus_initializers = [];
    let _ekycStatus_extraInitializers = [];
    let _ekycVerifiedAt_decorators;
    let _ekycVerifiedAt_initializers = [];
    let _ekycVerifiedAt_extraInitializers = [];
    let _ekycVerifiedBy_decorators;
    let _ekycVerifiedBy_initializers = [];
    let _ekycVerifiedBy_extraInitializers = [];
    let _ekycVerifiedById_decorators;
    let _ekycVerifiedById_initializers = [];
    let _ekycVerifiedById_extraInitializers = [];
    let _tags_decorators;
    let _tags_initializers = [];
    let _tags_extraInitializers = [];
    let _customerType_decorators;
    let _customerType_initializers = [];
    let _customerType_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    let _birthdayOffer_decorators;
    let _birthdayOffer_initializers = [];
    let _birthdayOffer_extraInitializers = [];
    let _notes_decorators;
    let _notes_initializers = [];
    let _notes_extraInitializers = [];
    let _createdBy_decorators;
    let _createdBy_initializers = [];
    let _createdBy_extraInitializers = [];
    let _createdById_decorators;
    let _createdById_initializers = [];
    let _createdById_extraInitializers = [];
    let _branch_decorators;
    let _branch_initializers = [];
    let _branch_extraInitializers = [];
    let _branchId_decorators;
    let _branchId_initializers = [];
    let _branchId_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var Client = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.firstName = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _firstName_initializers, void 0));
            this.lastName = (__runInitializers(this, _firstName_extraInitializers), __runInitializers(this, _lastName_initializers, void 0));
            this.phone = (__runInitializers(this, _lastName_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
            this.alternatePhone = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _alternatePhone_initializers, void 0));
            this.email = (__runInitializers(this, _alternatePhone_extraInitializers), __runInitializers(this, _email_initializers, void 0));
            this.gender = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _gender_initializers, void 0));
            this.dateOfBirth = (__runInitializers(this, _gender_extraInitializers), __runInitializers(this, _dateOfBirth_initializers, void 0));
            this.address = (__runInitializers(this, _dateOfBirth_extraInitializers), __runInitializers(this, _address_initializers, void 0));
            this.city = (__runInitializers(this, _address_extraInitializers), __runInitializers(this, _city_initializers, void 0));
            this.district = (__runInitializers(this, _city_extraInitializers), __runInitializers(this, _district_initializers, void 0));
            this.state = (__runInitializers(this, _district_extraInitializers), __runInitializers(this, _state_initializers, void 0));
            this.pincode = (__runInitializers(this, _state_extraInitializers), __runInitializers(this, _pincode_initializers, void 0));
            this.gstin = (__runInitializers(this, _pincode_extraInitializers), __runInitializers(this, _gstin_initializers, void 0));
            this.idProofType = (__runInitializers(this, _gstin_extraInitializers), __runInitializers(this, _idProofType_initializers, void 0));
            this.idProofNumber = (__runInitializers(this, _idProofType_extraInitializers), __runInitializers(this, _idProofNumber_initializers, void 0));
            this.ekycStatus = (__runInitializers(this, _idProofNumber_extraInitializers), __runInitializers(this, _ekycStatus_initializers, void 0));
            this.ekycVerifiedAt = (__runInitializers(this, _ekycStatus_extraInitializers), __runInitializers(this, _ekycVerifiedAt_initializers, void 0));
            // DB column is 'ekyc_verified_by' not 'ekyc_verified_by_id'
            this.ekycVerifiedBy = (__runInitializers(this, _ekycVerifiedAt_extraInitializers), __runInitializers(this, _ekycVerifiedBy_initializers, void 0));
            this.ekycVerifiedById = (__runInitializers(this, _ekycVerifiedBy_extraInitializers), __runInitializers(this, _ekycVerifiedById_initializers, void 0));
            // ekyc_documents not in DB schema — store as tags jsonb or skip
            this.tags = (__runInitializers(this, _ekycVerifiedById_extraInitializers), __runInitializers(this, _tags_initializers, void 0));
            // Virtual field for ekyc documents (stored in kyc_documents table separately)
            this.ekycDocuments = __runInitializers(this, _tags_extraInitializers);
            this.customerType = __runInitializers(this, _customerType_initializers, void 0);
            this.isActive = (__runInitializers(this, _customerType_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.birthdayOffer = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _birthdayOffer_initializers, void 0));
            this.notes = (__runInitializers(this, _birthdayOffer_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            // DB column is 'created_by' not 'created_by_id'
            this.createdBy = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _createdBy_initializers, void 0));
            this.createdById = (__runInitializers(this, _createdBy_extraInitializers), __runInitializers(this, _createdById_initializers, void 0));
            this.branch = (__runInitializers(this, _createdById_extraInitializers), __runInitializers(this, _branch_initializers, void 0));
            this.branchId = (__runInitializers(this, _branch_extraInitializers), __runInitializers(this, _branchId_initializers, void 0));
            this.createdAt = (__runInitializers(this, _branchId_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "Client");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _firstName_decorators = [Column({ name: 'first_name' })];
        _lastName_decorators = [Column({ name: 'last_name', nullable: true, type: 'varchar' })];
        _phone_decorators = [Column({ unique: true })];
        _alternatePhone_decorators = [Column({ name: 'alternate_phone', nullable: true, type: 'varchar' })];
        _email_decorators = [Column({ nullable: true, type: 'varchar' })];
        _gender_decorators = [Column({ nullable: true, type: 'varchar' })];
        _dateOfBirth_decorators = [Column({ name: 'date_of_birth', nullable: true, type: 'date' })];
        _address_decorators = [Column({ nullable: true, type: 'text' })];
        _city_decorators = [Column({ nullable: true, type: 'varchar' })];
        _district_decorators = [Column({ nullable: true, type: 'varchar' })];
        _state_decorators = [Column({ nullable: true, type: 'varchar' })];
        _pincode_decorators = [Column({ nullable: true, type: 'varchar' })];
        _gstin_decorators = [Column({ name: 'gstin', nullable: true, type: 'varchar', length: 20 })];
        _idProofType_decorators = [Column({ name: 'id_proof_type', nullable: true, type: 'varchar' })];
        _idProofNumber_decorators = [Column({ name: 'id_proof_number', nullable: true, type: 'varchar' })];
        _ekycStatus_decorators = [Column({ name: 'ekyc_status', default: 'pending' })];
        _ekycVerifiedAt_decorators = [Column({ name: 'ekyc_verified_at', nullable: true, type: 'timestamptz' })];
        _ekycVerifiedBy_decorators = [ManyToOne(() => User, { eager: false, nullable: true }), JoinColumn({ name: 'ekyc_verified_by' })];
        _ekycVerifiedById_decorators = [Column({ name: 'ekyc_verified_by', nullable: true, type: 'varchar' })];
        _tags_decorators = [Column({ nullable: true, type: 'jsonb' })];
        _customerType_decorators = [Column({ name: 'customer_type', default: 'walk-in' })];
        _isActive_decorators = [Column({ name: 'is_active', default: true })];
        _birthdayOffer_decorators = [Column({ name: 'birthday_offer', default: false })];
        _notes_decorators = [Column({ nullable: true, type: 'text' })];
        _createdBy_decorators = [ManyToOne(() => User, { eager: false, nullable: true }), JoinColumn({ name: 'created_by' })];
        _createdById_decorators = [Column({ name: 'created_by', nullable: true, type: 'varchar' })];
        _branch_decorators = [ManyToOne(() => Branch, { eager: false, nullable: true }), JoinColumn({ name: 'branch_id' })];
        _branchId_decorators = [Column({ name: 'branch_id', nullable: true, type: 'varchar' })];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        _updatedAt_decorators = [UpdateDateColumn({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _firstName_decorators, { kind: "field", name: "firstName", static: false, private: false, access: { has: obj => "firstName" in obj, get: obj => obj.firstName, set: (obj, value) => { obj.firstName = value; } }, metadata: _metadata }, _firstName_initializers, _firstName_extraInitializers);
        __esDecorate(null, null, _lastName_decorators, { kind: "field", name: "lastName", static: false, private: false, access: { has: obj => "lastName" in obj, get: obj => obj.lastName, set: (obj, value) => { obj.lastName = value; } }, metadata: _metadata }, _lastName_initializers, _lastName_extraInitializers);
        __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: obj => "phone" in obj, get: obj => obj.phone, set: (obj, value) => { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
        __esDecorate(null, null, _alternatePhone_decorators, { kind: "field", name: "alternatePhone", static: false, private: false, access: { has: obj => "alternatePhone" in obj, get: obj => obj.alternatePhone, set: (obj, value) => { obj.alternatePhone = value; } }, metadata: _metadata }, _alternatePhone_initializers, _alternatePhone_extraInitializers);
        __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: obj => "email" in obj, get: obj => obj.email, set: (obj, value) => { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
        __esDecorate(null, null, _gender_decorators, { kind: "field", name: "gender", static: false, private: false, access: { has: obj => "gender" in obj, get: obj => obj.gender, set: (obj, value) => { obj.gender = value; } }, metadata: _metadata }, _gender_initializers, _gender_extraInitializers);
        __esDecorate(null, null, _dateOfBirth_decorators, { kind: "field", name: "dateOfBirth", static: false, private: false, access: { has: obj => "dateOfBirth" in obj, get: obj => obj.dateOfBirth, set: (obj, value) => { obj.dateOfBirth = value; } }, metadata: _metadata }, _dateOfBirth_initializers, _dateOfBirth_extraInitializers);
        __esDecorate(null, null, _address_decorators, { kind: "field", name: "address", static: false, private: false, access: { has: obj => "address" in obj, get: obj => obj.address, set: (obj, value) => { obj.address = value; } }, metadata: _metadata }, _address_initializers, _address_extraInitializers);
        __esDecorate(null, null, _city_decorators, { kind: "field", name: "city", static: false, private: false, access: { has: obj => "city" in obj, get: obj => obj.city, set: (obj, value) => { obj.city = value; } }, metadata: _metadata }, _city_initializers, _city_extraInitializers);
        __esDecorate(null, null, _district_decorators, { kind: "field", name: "district", static: false, private: false, access: { has: obj => "district" in obj, get: obj => obj.district, set: (obj, value) => { obj.district = value; } }, metadata: _metadata }, _district_initializers, _district_extraInitializers);
        __esDecorate(null, null, _state_decorators, { kind: "field", name: "state", static: false, private: false, access: { has: obj => "state" in obj, get: obj => obj.state, set: (obj, value) => { obj.state = value; } }, metadata: _metadata }, _state_initializers, _state_extraInitializers);
        __esDecorate(null, null, _pincode_decorators, { kind: "field", name: "pincode", static: false, private: false, access: { has: obj => "pincode" in obj, get: obj => obj.pincode, set: (obj, value) => { obj.pincode = value; } }, metadata: _metadata }, _pincode_initializers, _pincode_extraInitializers);
        __esDecorate(null, null, _gstin_decorators, { kind: "field", name: "gstin", static: false, private: false, access: { has: obj => "gstin" in obj, get: obj => obj.gstin, set: (obj, value) => { obj.gstin = value; } }, metadata: _metadata }, _gstin_initializers, _gstin_extraInitializers);
        __esDecorate(null, null, _idProofType_decorators, { kind: "field", name: "idProofType", static: false, private: false, access: { has: obj => "idProofType" in obj, get: obj => obj.idProofType, set: (obj, value) => { obj.idProofType = value; } }, metadata: _metadata }, _idProofType_initializers, _idProofType_extraInitializers);
        __esDecorate(null, null, _idProofNumber_decorators, { kind: "field", name: "idProofNumber", static: false, private: false, access: { has: obj => "idProofNumber" in obj, get: obj => obj.idProofNumber, set: (obj, value) => { obj.idProofNumber = value; } }, metadata: _metadata }, _idProofNumber_initializers, _idProofNumber_extraInitializers);
        __esDecorate(null, null, _ekycStatus_decorators, { kind: "field", name: "ekycStatus", static: false, private: false, access: { has: obj => "ekycStatus" in obj, get: obj => obj.ekycStatus, set: (obj, value) => { obj.ekycStatus = value; } }, metadata: _metadata }, _ekycStatus_initializers, _ekycStatus_extraInitializers);
        __esDecorate(null, null, _ekycVerifiedAt_decorators, { kind: "field", name: "ekycVerifiedAt", static: false, private: false, access: { has: obj => "ekycVerifiedAt" in obj, get: obj => obj.ekycVerifiedAt, set: (obj, value) => { obj.ekycVerifiedAt = value; } }, metadata: _metadata }, _ekycVerifiedAt_initializers, _ekycVerifiedAt_extraInitializers);
        __esDecorate(null, null, _ekycVerifiedBy_decorators, { kind: "field", name: "ekycVerifiedBy", static: false, private: false, access: { has: obj => "ekycVerifiedBy" in obj, get: obj => obj.ekycVerifiedBy, set: (obj, value) => { obj.ekycVerifiedBy = value; } }, metadata: _metadata }, _ekycVerifiedBy_initializers, _ekycVerifiedBy_extraInitializers);
        __esDecorate(null, null, _ekycVerifiedById_decorators, { kind: "field", name: "ekycVerifiedById", static: false, private: false, access: { has: obj => "ekycVerifiedById" in obj, get: obj => obj.ekycVerifiedById, set: (obj, value) => { obj.ekycVerifiedById = value; } }, metadata: _metadata }, _ekycVerifiedById_initializers, _ekycVerifiedById_extraInitializers);
        __esDecorate(null, null, _tags_decorators, { kind: "field", name: "tags", static: false, private: false, access: { has: obj => "tags" in obj, get: obj => obj.tags, set: (obj, value) => { obj.tags = value; } }, metadata: _metadata }, _tags_initializers, _tags_extraInitializers);
        __esDecorate(null, null, _customerType_decorators, { kind: "field", name: "customerType", static: false, private: false, access: { has: obj => "customerType" in obj, get: obj => obj.customerType, set: (obj, value) => { obj.customerType = value; } }, metadata: _metadata }, _customerType_initializers, _customerType_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _birthdayOffer_decorators, { kind: "field", name: "birthdayOffer", static: false, private: false, access: { has: obj => "birthdayOffer" in obj, get: obj => obj.birthdayOffer, set: (obj, value) => { obj.birthdayOffer = value; } }, metadata: _metadata }, _birthdayOffer_initializers, _birthdayOffer_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: obj => "notes" in obj, get: obj => obj.notes, set: (obj, value) => { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _createdBy_decorators, { kind: "field", name: "createdBy", static: false, private: false, access: { has: obj => "createdBy" in obj, get: obj => obj.createdBy, set: (obj, value) => { obj.createdBy = value; } }, metadata: _metadata }, _createdBy_initializers, _createdBy_extraInitializers);
        __esDecorate(null, null, _createdById_decorators, { kind: "field", name: "createdById", static: false, private: false, access: { has: obj => "createdById" in obj, get: obj => obj.createdById, set: (obj, value) => { obj.createdById = value; } }, metadata: _metadata }, _createdById_initializers, _createdById_extraInitializers);
        __esDecorate(null, null, _branch_decorators, { kind: "field", name: "branch", static: false, private: false, access: { has: obj => "branch" in obj, get: obj => obj.branch, set: (obj, value) => { obj.branch = value; } }, metadata: _metadata }, _branch_initializers, _branch_extraInitializers);
        __esDecorate(null, null, _branchId_decorators, { kind: "field", name: "branchId", static: false, private: false, access: { has: obj => "branchId" in obj, get: obj => obj.branchId, set: (obj, value) => { obj.branchId = value; } }, metadata: _metadata }, _branchId_initializers, _branchId_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Client = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Client = _classThis;
})();
export { Client };
//# sourceMappingURL=client.entity.js.map