'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function PriceComparison({ brand, modelName, refurbishedPrice, newPrice }) {
    if (!newPrice || newPrice <= refurbishedPrice)
        return null;
    const savings = newPrice - refurbishedPrice;
    const savingsPercent = Math.round((savings / newPrice) * 100);
    return (_jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "heading-sm text-surface-900", children: "Compare vs New" }), _jsxs("div", { className: "border border-surface-200 rounded-2xl overflow-hidden divide-y divide-surface-100", children: [_jsxs("div", { className: "compare-row bg-surface-50", children: [_jsx("span", { className: "text-surface-500", children: "Condition" }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-semibold text-surface-900", children: "Refurbished" }), _jsx("p", { className: "text-xs text-surface-400", children: "Certified, tested, like-new" })] })] }), _jsxs("div", { className: "compare-row", children: [_jsx("span", { className: "text-surface-500", children: "Price" }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-lg font-extrabold text-primary", children: ["\u20B9", refurbishedPrice.toLocaleString('en-IN')] }), _jsxs("p", { className: "text-sm text-surface-400 line-through", children: ["\u20B9", newPrice.toLocaleString('en-IN')] })] })] }), _jsxs("div", { className: "compare-row bg-emerald-50", children: [_jsx("span", { className: "text-surface-500", children: "You Save" }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-lg font-extrabold text-emerald-600", children: ["\u20B9", savings.toLocaleString('en-IN')] }), _jsxs("span", { className: "inline-block text-xs font-semibold text-emerald-600 bg-emerald-100 px-2 py-0.5 rounded-full", children: [savingsPercent, "% OFF"] })] })] }), _jsxs("div", { className: "compare-row bg-surface-50", children: [_jsx("span", { className: "text-surface-500", children: "Warranty" }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-semibold text-surface-900", children: "Free 30-Day Warranty" }), _jsx("p", { className: "text-xs text-surface-400", children: "Same as new device warranty" })] })] }), _jsxs("div", { className: "compare-row", children: [_jsx("span", { className: "text-surface-500", children: "Returns" }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-semibold text-surface-900", children: "7-Day Returns" }), _jsx("p", { className: "text-xs text-surface-400", children: "No questions asked" })] })] })] }), _jsxs("div", { className: "p-4 bg-primary/5 rounded-2xl border border-primary/10", children: [_jsx("p", { className: "text-sm font-semibold text-surface-900 mb-1", children: "\u2728 Why choose refurbished?" }), _jsx("p", { className: "text-xs text-surface-500", children: "You get the same device experience at a fraction of the cost. Every device goes through our 20-point quality check and comes with warranty. Plus, you're helping reduce e-waste!" })] })] }));
}
//# sourceMappingURL=PriceComparison.js.map