var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn, UpdateDateColumn, JoinColumn, } from 'typeorm';
import { Brand } from './brand.entity';
import { Model } from './model.entity';
import { Branch } from '../../auth/entities/user.entity';
import { User } from '../../auth/entities/user.entity';
let Accessory = (() => {
    let _classDecorators = [Entity('accessories')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _sku_decorators;
    let _sku_initializers = [];
    let _sku_extraInitializers = [];
    let _name_decorators;
    let _name_initializers = [];
    let _name_extraInitializers = [];
    let _description_decorators;
    let _description_initializers = [];
    let _description_extraInitializers = [];
    let _brand_decorators;
    let _brand_initializers = [];
    let _brand_extraInitializers = [];
    let _brandId_decorators;
    let _brandId_initializers = [];
    let _brandId_extraInitializers = [];
    let _model_decorators;
    let _model_initializers = [];
    let _model_extraInitializers = [];
    let _modelId_decorators;
    let _modelId_initializers = [];
    let _modelId_extraInitializers = [];
    let _category_decorators;
    let _category_initializers = [];
    let _category_extraInitializers = [];
    let _purchasePrice_decorators;
    let _purchasePrice_initializers = [];
    let _purchasePrice_extraInitializers = [];
    let _sellingPrice_decorators;
    let _sellingPrice_initializers = [];
    let _sellingPrice_extraInitializers = [];
    let _wholesalePrice_decorators;
    let _wholesalePrice_initializers = [];
    let _wholesalePrice_extraInitializers = [];
    let _stockQuantity_decorators;
    let _stockQuantity_initializers = [];
    let _stockQuantity_extraInitializers = [];
    let _reorderLevel_decorators;
    let _reorderLevel_initializers = [];
    let _reorderLevel_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    let _isOnline_decorators;
    let _isOnline_initializers = [];
    let _isOnline_extraInitializers = [];
    let _hsnCode_decorators;
    let _hsnCode_initializers = [];
    let _hsnCode_extraInitializers = [];
    let _taxRate_decorators;
    let _taxRate_initializers = [];
    let _taxRate_extraInitializers = [];
    let _notes_decorators;
    let _notes_initializers = [];
    let _notes_extraInitializers = [];
    let _branch_decorators;
    let _branch_initializers = [];
    let _branch_extraInitializers = [];
    let _branchId_decorators;
    let _branchId_initializers = [];
    let _branchId_extraInitializers = [];
    let _specs_decorators;
    let _specs_initializers = [];
    let _specs_extraInitializers = [];
    let _photos_decorators;
    let _photos_initializers = [];
    let _photos_extraInitializers = [];
    let _createdBy_decorators;
    let _createdBy_initializers = [];
    let _createdBy_extraInitializers = [];
    let _createdById_decorators;
    let _createdById_initializers = [];
    let _createdById_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var Accessory = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.sku = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _sku_initializers, void 0));
            this.name = (__runInitializers(this, _sku_extraInitializers), __runInitializers(this, _name_initializers, void 0));
            this.description = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _description_initializers, void 0));
            this.brand = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _brand_initializers, void 0));
            this.brandId = (__runInitializers(this, _brand_extraInitializers), __runInitializers(this, _brandId_initializers, void 0));
            this.model = (__runInitializers(this, _brandId_extraInitializers), __runInitializers(this, _model_initializers, void 0));
            this.modelId = (__runInitializers(this, _model_extraInitializers), __runInitializers(this, _modelId_initializers, void 0));
            this.category = (__runInitializers(this, _modelId_extraInitializers), __runInitializers(this, _category_initializers, void 0)); // charger, case, screen_guard, earphones, cable, power_bank, etc.
            this.purchasePrice = (__runInitializers(this, _category_extraInitializers), __runInitializers(this, _purchasePrice_initializers, void 0));
            this.sellingPrice = (__runInitializers(this, _purchasePrice_extraInitializers), __runInitializers(this, _sellingPrice_initializers, void 0));
            this.wholesalePrice = (__runInitializers(this, _sellingPrice_extraInitializers), __runInitializers(this, _wholesalePrice_initializers, void 0));
            this.stockQuantity = (__runInitializers(this, _wholesalePrice_extraInitializers), __runInitializers(this, _stockQuantity_initializers, void 0));
            this.reorderLevel = (__runInitializers(this, _stockQuantity_extraInitializers), __runInitializers(this, _reorderLevel_initializers, void 0));
            this.status = (__runInitializers(this, _reorderLevel_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.isOnline = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _isOnline_initializers, void 0));
            this.hsnCode = (__runInitializers(this, _isOnline_extraInitializers), __runInitializers(this, _hsnCode_initializers, void 0));
            this.taxRate = (__runInitializers(this, _hsnCode_extraInitializers), __runInitializers(this, _taxRate_initializers, void 0));
            this.notes = (__runInitializers(this, _taxRate_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.branch = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _branch_initializers, void 0));
            this.branchId = (__runInitializers(this, _branch_extraInitializers), __runInitializers(this, _branchId_initializers, void 0));
            this.specs = (__runInitializers(this, _branchId_extraInitializers), __runInitializers(this, _specs_initializers, void 0));
            this.photos = (__runInitializers(this, _specs_extraInitializers), __runInitializers(this, _photos_initializers, void 0));
            this.createdBy = (__runInitializers(this, _photos_extraInitializers), __runInitializers(this, _createdBy_initializers, void 0));
            this.createdById = (__runInitializers(this, _createdBy_extraInitializers), __runInitializers(this, _createdById_initializers, void 0));
            this.createdAt = (__runInitializers(this, _createdById_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "Accessory");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _sku_decorators = [Column({ unique: true, length: 50 })];
        _name_decorators = [Column({ type: 'varchar', length: 100 })];
        _description_decorators = [Column({ type: 'varchar', length: 200, nullable: true })];
        _brand_decorators = [ManyToOne(() => Brand, { eager: false, nullable: true }), JoinColumn({ name: 'brand_id' })];
        _brandId_decorators = [Column({ name: 'brand_id', nullable: true, type: 'uuid' })];
        _model_decorators = [ManyToOne(() => Model, { eager: false, nullable: true }), JoinColumn({ name: 'model_id' })];
        _modelId_decorators = [Column({ name: 'model_id', nullable: true, type: 'uuid' })];
        _category_decorators = [Column({ type: 'varchar', length: 50 })];
        _purchasePrice_decorators = [Column({ type: 'decimal', precision: 12, scale: 2 })];
        _sellingPrice_decorators = [Column({ type: 'decimal', precision: 12, scale: 2, nullable: true })];
        _wholesalePrice_decorators = [Column({ type: 'decimal', precision: 12, scale: 2, nullable: true })];
        _stockQuantity_decorators = [Column({ type: 'smallint', default: 0 })];
        _reorderLevel_decorators = [Column({ type: 'smallint', default: 10 })];
        _status_decorators = [Column({ type: 'varchar', length: 20, default: 'available' })];
        _isOnline_decorators = [Column({ type: 'boolean', default: false })];
        _hsnCode_decorators = [Column({ type: 'varchar', length: 50, nullable: true })];
        _taxRate_decorators = [Column({ type: 'decimal', precision: 5, scale: 2, default: 0 })];
        _notes_decorators = [Column({ type: 'text', nullable: true })];
        _branch_decorators = [ManyToOne(() => Branch, { eager: false, nullable: true }), JoinColumn({ name: 'branch_id' })];
        _branchId_decorators = [Column({ name: 'branch_id', nullable: true, type: 'uuid' })];
        _specs_decorators = [Column({ type: 'jsonb', nullable: true })];
        _photos_decorators = [Column({ type: 'jsonb', nullable: true })];
        _createdBy_decorators = [ManyToOne(() => User, { eager: false, nullable: true }), JoinColumn({ name: 'created_by_id' })];
        _createdById_decorators = [Column({ name: 'created_by_id', nullable: true, type: 'uuid' })];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        _updatedAt_decorators = [UpdateDateColumn({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _sku_decorators, { kind: "field", name: "sku", static: false, private: false, access: { has: obj => "sku" in obj, get: obj => obj.sku, set: (obj, value) => { obj.sku = value; } }, metadata: _metadata }, _sku_initializers, _sku_extraInitializers);
        __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: obj => "name" in obj, get: obj => obj.name, set: (obj, value) => { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
        __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: obj => "description" in obj, get: obj => obj.description, set: (obj, value) => { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
        __esDecorate(null, null, _brand_decorators, { kind: "field", name: "brand", static: false, private: false, access: { has: obj => "brand" in obj, get: obj => obj.brand, set: (obj, value) => { obj.brand = value; } }, metadata: _metadata }, _brand_initializers, _brand_extraInitializers);
        __esDecorate(null, null, _brandId_decorators, { kind: "field", name: "brandId", static: false, private: false, access: { has: obj => "brandId" in obj, get: obj => obj.brandId, set: (obj, value) => { obj.brandId = value; } }, metadata: _metadata }, _brandId_initializers, _brandId_extraInitializers);
        __esDecorate(null, null, _model_decorators, { kind: "field", name: "model", static: false, private: false, access: { has: obj => "model" in obj, get: obj => obj.model, set: (obj, value) => { obj.model = value; } }, metadata: _metadata }, _model_initializers, _model_extraInitializers);
        __esDecorate(null, null, _modelId_decorators, { kind: "field", name: "modelId", static: false, private: false, access: { has: obj => "modelId" in obj, get: obj => obj.modelId, set: (obj, value) => { obj.modelId = value; } }, metadata: _metadata }, _modelId_initializers, _modelId_extraInitializers);
        __esDecorate(null, null, _category_decorators, { kind: "field", name: "category", static: false, private: false, access: { has: obj => "category" in obj, get: obj => obj.category, set: (obj, value) => { obj.category = value; } }, metadata: _metadata }, _category_initializers, _category_extraInitializers);
        __esDecorate(null, null, _purchasePrice_decorators, { kind: "field", name: "purchasePrice", static: false, private: false, access: { has: obj => "purchasePrice" in obj, get: obj => obj.purchasePrice, set: (obj, value) => { obj.purchasePrice = value; } }, metadata: _metadata }, _purchasePrice_initializers, _purchasePrice_extraInitializers);
        __esDecorate(null, null, _sellingPrice_decorators, { kind: "field", name: "sellingPrice", static: false, private: false, access: { has: obj => "sellingPrice" in obj, get: obj => obj.sellingPrice, set: (obj, value) => { obj.sellingPrice = value; } }, metadata: _metadata }, _sellingPrice_initializers, _sellingPrice_extraInitializers);
        __esDecorate(null, null, _wholesalePrice_decorators, { kind: "field", name: "wholesalePrice", static: false, private: false, access: { has: obj => "wholesalePrice" in obj, get: obj => obj.wholesalePrice, set: (obj, value) => { obj.wholesalePrice = value; } }, metadata: _metadata }, _wholesalePrice_initializers, _wholesalePrice_extraInitializers);
        __esDecorate(null, null, _stockQuantity_decorators, { kind: "field", name: "stockQuantity", static: false, private: false, access: { has: obj => "stockQuantity" in obj, get: obj => obj.stockQuantity, set: (obj, value) => { obj.stockQuantity = value; } }, metadata: _metadata }, _stockQuantity_initializers, _stockQuantity_extraInitializers);
        __esDecorate(null, null, _reorderLevel_decorators, { kind: "field", name: "reorderLevel", static: false, private: false, access: { has: obj => "reorderLevel" in obj, get: obj => obj.reorderLevel, set: (obj, value) => { obj.reorderLevel = value; } }, metadata: _metadata }, _reorderLevel_initializers, _reorderLevel_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _isOnline_decorators, { kind: "field", name: "isOnline", static: false, private: false, access: { has: obj => "isOnline" in obj, get: obj => obj.isOnline, set: (obj, value) => { obj.isOnline = value; } }, metadata: _metadata }, _isOnline_initializers, _isOnline_extraInitializers);
        __esDecorate(null, null, _hsnCode_decorators, { kind: "field", name: "hsnCode", static: false, private: false, access: { has: obj => "hsnCode" in obj, get: obj => obj.hsnCode, set: (obj, value) => { obj.hsnCode = value; } }, metadata: _metadata }, _hsnCode_initializers, _hsnCode_extraInitializers);
        __esDecorate(null, null, _taxRate_decorators, { kind: "field", name: "taxRate", static: false, private: false, access: { has: obj => "taxRate" in obj, get: obj => obj.taxRate, set: (obj, value) => { obj.taxRate = value; } }, metadata: _metadata }, _taxRate_initializers, _taxRate_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: obj => "notes" in obj, get: obj => obj.notes, set: (obj, value) => { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _branch_decorators, { kind: "field", name: "branch", static: false, private: false, access: { has: obj => "branch" in obj, get: obj => obj.branch, set: (obj, value) => { obj.branch = value; } }, metadata: _metadata }, _branch_initializers, _branch_extraInitializers);
        __esDecorate(null, null, _branchId_decorators, { kind: "field", name: "branchId", static: false, private: false, access: { has: obj => "branchId" in obj, get: obj => obj.branchId, set: (obj, value) => { obj.branchId = value; } }, metadata: _metadata }, _branchId_initializers, _branchId_extraInitializers);
        __esDecorate(null, null, _specs_decorators, { kind: "field", name: "specs", static: false, private: false, access: { has: obj => "specs" in obj, get: obj => obj.specs, set: (obj, value) => { obj.specs = value; } }, metadata: _metadata }, _specs_initializers, _specs_extraInitializers);
        __esDecorate(null, null, _photos_decorators, { kind: "field", name: "photos", static: false, private: false, access: { has: obj => "photos" in obj, get: obj => obj.photos, set: (obj, value) => { obj.photos = value; } }, metadata: _metadata }, _photos_initializers, _photos_extraInitializers);
        __esDecorate(null, null, _createdBy_decorators, { kind: "field", name: "createdBy", static: false, private: false, access: { has: obj => "createdBy" in obj, get: obj => obj.createdBy, set: (obj, value) => { obj.createdBy = value; } }, metadata: _metadata }, _createdBy_initializers, _createdBy_extraInitializers);
        __esDecorate(null, null, _createdById_decorators, { kind: "field", name: "createdById", static: false, private: false, access: { has: obj => "createdById" in obj, get: obj => obj.createdById, set: (obj, value) => { obj.createdById = value; } }, metadata: _metadata }, _createdById_initializers, _createdById_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Accessory = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Accessory = _classThis;
})();
export { Accessory };
//# sourceMappingURL=accessory.entity.js.map