var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, OneToMany, JoinColumn, CreateDateColumn, UpdateDateColumn, } from 'typeorm';
import { Brand } from './brand.entity';
import { Model } from './model.entity';
import { Branch, User } from '../../auth/entities/user.entity';
import { ItemPhoto } from './item-photo.entity';
let InventoryItem = (() => {
    let _classDecorators = [Entity('inventory_items')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _imei_decorators;
    let _imei_initializers = [];
    let _imei_extraInitializers = [];
    let _imei2_decorators;
    let _imei2_initializers = [];
    let _imei2_extraInitializers = [];
    let _brand_decorators;
    let _brand_initializers = [];
    let _brand_extraInitializers = [];
    let _brandId_decorators;
    let _brandId_initializers = [];
    let _brandId_extraInitializers = [];
    let _model_decorators;
    let _model_initializers = [];
    let _model_extraInitializers = [];
    let _modelId_decorators;
    let _modelId_initializers = [];
    let _modelId_extraInitializers = [];
    let _colour_decorators;
    let _colour_initializers = [];
    let _colour_extraInitializers = [];
    let _storage_decorators;
    let _storage_initializers = [];
    let _storage_extraInitializers = [];
    let _ram_decorators;
    let _ram_initializers = [];
    let _ram_extraInitializers = [];
    let _boxType_decorators;
    let _boxType_initializers = [];
    let _boxType_extraInitializers = [];
    let _pkuCode_decorators;
    let _pkuCode_initializers = [];
    let _pkuCode_extraInitializers = [];
    let _batteryHealth_decorators;
    let _batteryHealth_initializers = [];
    let _batteryHealth_extraInitializers = [];
    let _countryOfOrigin_decorators;
    let _countryOfOrigin_initializers = [];
    let _countryOfOrigin_extraInitializers = [];
    let _hsnCode_decorators;
    let _hsnCode_initializers = [];
    let _hsnCode_extraInitializers = [];
    let _condition_decorators;
    let _condition_initializers = [];
    let _condition_extraInitializers = [];
    let _itemName_decorators;
    let _itemName_initializers = [];
    let _itemName_extraInitializers = [];
    let _firstInvoiceDate_decorators;
    let _firstInvoiceDate_initializers = [];
    let _firstInvoiceDate_extraInitializers = [];
    let _purchasePrice_decorators;
    let _purchasePrice_initializers = [];
    let _purchasePrice_extraInitializers = [];
    let _wholesalePrice_decorators;
    let _wholesalePrice_initializers = [];
    let _wholesalePrice_extraInitializers = [];
    let _boxPrice_decorators;
    let _boxPrice_initializers = [];
    let _boxPrice_extraInitializers = [];
    let _taxRate_decorators;
    let _taxRate_initializers = [];
    let _taxRate_extraInitializers = [];
    let _taxAmount_decorators;
    let _taxAmount_initializers = [];
    let _taxAmount_extraInitializers = [];
    let _totalCost_decorators;
    let _totalCost_initializers = [];
    let _totalCost_extraInitializers = [];
    let _sellingPrice_decorators;
    let _sellingPrice_initializers = [];
    let _sellingPrice_extraInitializers = [];
    let _onlinePrice_decorators;
    let _onlinePrice_initializers = [];
    let _onlinePrice_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    let _isOnline_decorators;
    let _isOnline_initializers = [];
    let _isOnline_extraInitializers = [];
    let _birthdayOffer_decorators;
    let _birthdayOffer_initializers = [];
    let _birthdayOffer_extraInitializers = [];
    let _branch_decorators;
    let _branch_initializers = [];
    let _branch_extraInitializers = [];
    let _branchId_decorators;
    let _branchId_initializers = [];
    let _branchId_extraInitializers = [];
    let _purchaseId_decorators;
    let _purchaseId_initializers = [];
    let _purchaseId_extraInitializers = [];
    let _notes_decorators;
    let _notes_initializers = [];
    let _notes_extraInitializers = [];
    let _accessories_decorators;
    let _accessories_initializers = [];
    let _accessories_extraInitializers = [];
    let _images_decorators;
    let _images_initializers = [];
    let _images_extraInitializers = [];
    let _warrantyStatus_decorators;
    let _warrantyStatus_initializers = [];
    let _warrantyStatus_extraInitializers = [];
    let _warrantyExpiry_decorators;
    let _warrantyExpiry_initializers = [];
    let _warrantyExpiry_extraInitializers = [];
    let _createdBy_decorators;
    let _createdBy_initializers = [];
    let _createdBy_extraInitializers = [];
    let _createdById_decorators;
    let _createdById_initializers = [];
    let _createdById_extraInitializers = [];
    let _photos_decorators;
    let _photos_initializers = [];
    let _photos_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var InventoryItem = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.imei = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _imei_initializers, void 0));
            this.imei2 = (__runInitializers(this, _imei_extraInitializers), __runInitializers(this, _imei2_initializers, void 0));
            this.brand = (__runInitializers(this, _imei2_extraInitializers), __runInitializers(this, _brand_initializers, void 0));
            this.brandId = (__runInitializers(this, _brand_extraInitializers), __runInitializers(this, _brandId_initializers, void 0));
            this.model = (__runInitializers(this, _brandId_extraInitializers), __runInitializers(this, _model_initializers, void 0));
            this.modelId = (__runInitializers(this, _model_extraInitializers), __runInitializers(this, _modelId_initializers, void 0));
            this.colour = (__runInitializers(this, _modelId_extraInitializers), __runInitializers(this, _colour_initializers, void 0));
            this.storage = (__runInitializers(this, _colour_extraInitializers), __runInitializers(this, _storage_initializers, void 0));
            this.ram = (__runInitializers(this, _storage_extraInitializers), __runInitializers(this, _ram_initializers, void 0));
            this.boxType = (__runInitializers(this, _ram_extraInitializers), __runInitializers(this, _boxType_initializers, void 0));
            this.pkuCode = (__runInitializers(this, _boxType_extraInitializers), __runInitializers(this, _pkuCode_initializers, void 0));
            this.batteryHealth = (__runInitializers(this, _pkuCode_extraInitializers), __runInitializers(this, _batteryHealth_initializers, void 0));
            this.countryOfOrigin = (__runInitializers(this, _batteryHealth_extraInitializers), __runInitializers(this, _countryOfOrigin_initializers, void 0));
            this.hsnCode = (__runInitializers(this, _countryOfOrigin_extraInitializers), __runInitializers(this, _hsnCode_initializers, void 0));
            this.condition = (__runInitializers(this, _hsnCode_extraInitializers), __runInitializers(this, _condition_initializers, void 0));
            this.itemName = (__runInitializers(this, _condition_extraInitializers), __runInitializers(this, _itemName_initializers, void 0));
            this.firstInvoiceDate = (__runInitializers(this, _itemName_extraInitializers), __runInitializers(this, _firstInvoiceDate_initializers, void 0));
            this.purchasePrice = (__runInitializers(this, _firstInvoiceDate_extraInitializers), __runInitializers(this, _purchasePrice_initializers, void 0));
            this.wholesalePrice = (__runInitializers(this, _purchasePrice_extraInitializers), __runInitializers(this, _wholesalePrice_initializers, void 0));
            this.boxPrice = (__runInitializers(this, _wholesalePrice_extraInitializers), __runInitializers(this, _boxPrice_initializers, void 0));
            this.taxRate = (__runInitializers(this, _boxPrice_extraInitializers), __runInitializers(this, _taxRate_initializers, void 0));
            this.taxAmount = (__runInitializers(this, _taxRate_extraInitializers), __runInitializers(this, _taxAmount_initializers, void 0));
            this.totalCost = (__runInitializers(this, _taxAmount_extraInitializers), __runInitializers(this, _totalCost_initializers, void 0));
            this.sellingPrice = (__runInitializers(this, _totalCost_extraInitializers), __runInitializers(this, _sellingPrice_initializers, void 0));
            this.onlinePrice = (__runInitializers(this, _sellingPrice_extraInitializers), __runInitializers(this, _onlinePrice_initializers, void 0));
            this.status = (__runInitializers(this, _onlinePrice_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.isOnline = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _isOnline_initializers, void 0));
            this.birthdayOffer = (__runInitializers(this, _isOnline_extraInitializers), __runInitializers(this, _birthdayOffer_initializers, void 0));
            this.branch = (__runInitializers(this, _birthdayOffer_extraInitializers), __runInitializers(this, _branch_initializers, void 0));
            this.branchId = (__runInitializers(this, _branch_extraInitializers), __runInitializers(this, _branchId_initializers, void 0));
            this.purchaseId = (__runInitializers(this, _branchId_extraInitializers), __runInitializers(this, _purchaseId_initializers, void 0));
            this.notes = (__runInitializers(this, _purchaseId_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.accessories = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _accessories_initializers, void 0));
            this.images = (__runInitializers(this, _accessories_extraInitializers), __runInitializers(this, _images_initializers, void 0));
            this.warrantyStatus = (__runInitializers(this, _images_extraInitializers), __runInitializers(this, _warrantyStatus_initializers, void 0));
            this.warrantyExpiry = (__runInitializers(this, _warrantyStatus_extraInitializers), __runInitializers(this, _warrantyExpiry_initializers, void 0));
            // DB column is 'created_by' not 'created_by_id'
            this.createdBy = (__runInitializers(this, _warrantyExpiry_extraInitializers), __runInitializers(this, _createdBy_initializers, void 0));
            this.createdById = (__runInitializers(this, _createdBy_extraInitializers), __runInitializers(this, _createdById_initializers, void 0));
            this.photos = (__runInitializers(this, _createdById_extraInitializers), __runInitializers(this, _photos_initializers, void 0));
            this.createdAt = (__runInitializers(this, _photos_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "InventoryItem");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _imei_decorators = [Column({ unique: true, length: 15 })];
        _imei2_decorators = [Column({ nullable: true, type: 'varchar', length: 15 })];
        _brand_decorators = [ManyToOne(() => Brand, { eager: false, nullable: true }), JoinColumn({ name: 'brand_id' })];
        _brandId_decorators = [Column({ name: 'brand_id', nullable: true, type: 'varchar' })];
        _model_decorators = [ManyToOne(() => Model, { eager: false, nullable: true }), JoinColumn({ name: 'model_id' })];
        _modelId_decorators = [Column({ name: 'model_id', nullable: true, type: 'varchar' })];
        _colour_decorators = [Column({ nullable: true, type: 'varchar' })];
        _storage_decorators = [Column({ nullable: true, type: 'varchar' })];
        _ram_decorators = [Column({ nullable: true, type: 'varchar' })];
        _boxType_decorators = [Column({ name: 'box_type' })];
        _pkuCode_decorators = [Column({ name: 'pku_code', nullable: true, type: 'varchar' })];
        _batteryHealth_decorators = [Column({ name: 'battery_health', nullable: true, type: 'smallint' })];
        _countryOfOrigin_decorators = [Column({ name: 'country_of_origin', nullable: true, type: 'varchar' })];
        _hsnCode_decorators = [Column({ name: 'hsn_code', nullable: true, type: 'varchar' })];
        _condition_decorators = [Column()];
        _itemName_decorators = [Column({ name: 'item_name', nullable: true, type: 'varchar' })];
        _firstInvoiceDate_decorators = [Column({ name: 'first_invoice_date', nullable: true, type: 'date' })];
        _purchasePrice_decorators = [Column('decimal', { name: 'purchase_price', precision: 12, scale: 2 })];
        _wholesalePrice_decorators = [Column('decimal', { name: 'wholesale_price', precision: 12, scale: 2, nullable: true })];
        _boxPrice_decorators = [Column('decimal', { name: 'box_price', precision: 12, scale: 2, nullable: true })];
        _taxRate_decorators = [Column('decimal', { name: 'tax_rate', precision: 5, scale: 2, default: 0 })];
        _taxAmount_decorators = [Column('decimal', { name: 'tax_amount', precision: 12, scale: 2, default: 0 })];
        _totalCost_decorators = [Column('decimal', { name: 'total_cost', precision: 12, scale: 2 })];
        _sellingPrice_decorators = [Column('decimal', { name: 'selling_price', precision: 12, scale: 2, nullable: true })];
        _onlinePrice_decorators = [Column('decimal', { name: 'online_price', precision: 12, scale: 2, nullable: true })];
        _status_decorators = [Column({ default: 'available' })];
        _isOnline_decorators = [Column({ name: 'is_online', default: false })];
        _birthdayOffer_decorators = [Column({ name: 'birthday_offer', default: false })];
        _branch_decorators = [ManyToOne(() => Branch, { eager: false, nullable: true }), JoinColumn({ name: 'branch_id' })];
        _branchId_decorators = [Column({ name: 'branch_id', nullable: true, type: 'varchar' })];
        _purchaseId_decorators = [Column({ name: 'purchase_id', nullable: true, type: 'uuid' })];
        _notes_decorators = [Column({ nullable: true, type: 'text' })];
        _accessories_decorators = [Column({ nullable: true, type: 'jsonb' })];
        _images_decorators = [Column({ nullable: true, type: 'jsonb', default: () => "'[]'" })];
        _warrantyStatus_decorators = [Column({ name: 'warranty_status', nullable: true, type: 'varchar' })];
        _warrantyExpiry_decorators = [Column({ name: 'warranty_expiry', nullable: true, type: 'date' })];
        _createdBy_decorators = [ManyToOne(() => User, { eager: false, nullable: true }), JoinColumn({ name: 'created_by' })];
        _createdById_decorators = [Column({ name: 'created_by', nullable: true, type: 'varchar' })];
        _photos_decorators = [OneToMany(() => ItemPhoto, (p) => p.item)];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        _updatedAt_decorators = [UpdateDateColumn({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _imei_decorators, { kind: "field", name: "imei", static: false, private: false, access: { has: obj => "imei" in obj, get: obj => obj.imei, set: (obj, value) => { obj.imei = value; } }, metadata: _metadata }, _imei_initializers, _imei_extraInitializers);
        __esDecorate(null, null, _imei2_decorators, { kind: "field", name: "imei2", static: false, private: false, access: { has: obj => "imei2" in obj, get: obj => obj.imei2, set: (obj, value) => { obj.imei2 = value; } }, metadata: _metadata }, _imei2_initializers, _imei2_extraInitializers);
        __esDecorate(null, null, _brand_decorators, { kind: "field", name: "brand", static: false, private: false, access: { has: obj => "brand" in obj, get: obj => obj.brand, set: (obj, value) => { obj.brand = value; } }, metadata: _metadata }, _brand_initializers, _brand_extraInitializers);
        __esDecorate(null, null, _brandId_decorators, { kind: "field", name: "brandId", static: false, private: false, access: { has: obj => "brandId" in obj, get: obj => obj.brandId, set: (obj, value) => { obj.brandId = value; } }, metadata: _metadata }, _brandId_initializers, _brandId_extraInitializers);
        __esDecorate(null, null, _model_decorators, { kind: "field", name: "model", static: false, private: false, access: { has: obj => "model" in obj, get: obj => obj.model, set: (obj, value) => { obj.model = value; } }, metadata: _metadata }, _model_initializers, _model_extraInitializers);
        __esDecorate(null, null, _modelId_decorators, { kind: "field", name: "modelId", static: false, private: false, access: { has: obj => "modelId" in obj, get: obj => obj.modelId, set: (obj, value) => { obj.modelId = value; } }, metadata: _metadata }, _modelId_initializers, _modelId_extraInitializers);
        __esDecorate(null, null, _colour_decorators, { kind: "field", name: "colour", static: false, private: false, access: { has: obj => "colour" in obj, get: obj => obj.colour, set: (obj, value) => { obj.colour = value; } }, metadata: _metadata }, _colour_initializers, _colour_extraInitializers);
        __esDecorate(null, null, _storage_decorators, { kind: "field", name: "storage", static: false, private: false, access: { has: obj => "storage" in obj, get: obj => obj.storage, set: (obj, value) => { obj.storage = value; } }, metadata: _metadata }, _storage_initializers, _storage_extraInitializers);
        __esDecorate(null, null, _ram_decorators, { kind: "field", name: "ram", static: false, private: false, access: { has: obj => "ram" in obj, get: obj => obj.ram, set: (obj, value) => { obj.ram = value; } }, metadata: _metadata }, _ram_initializers, _ram_extraInitializers);
        __esDecorate(null, null, _boxType_decorators, { kind: "field", name: "boxType", static: false, private: false, access: { has: obj => "boxType" in obj, get: obj => obj.boxType, set: (obj, value) => { obj.boxType = value; } }, metadata: _metadata }, _boxType_initializers, _boxType_extraInitializers);
        __esDecorate(null, null, _pkuCode_decorators, { kind: "field", name: "pkuCode", static: false, private: false, access: { has: obj => "pkuCode" in obj, get: obj => obj.pkuCode, set: (obj, value) => { obj.pkuCode = value; } }, metadata: _metadata }, _pkuCode_initializers, _pkuCode_extraInitializers);
        __esDecorate(null, null, _batteryHealth_decorators, { kind: "field", name: "batteryHealth", static: false, private: false, access: { has: obj => "batteryHealth" in obj, get: obj => obj.batteryHealth, set: (obj, value) => { obj.batteryHealth = value; } }, metadata: _metadata }, _batteryHealth_initializers, _batteryHealth_extraInitializers);
        __esDecorate(null, null, _countryOfOrigin_decorators, { kind: "field", name: "countryOfOrigin", static: false, private: false, access: { has: obj => "countryOfOrigin" in obj, get: obj => obj.countryOfOrigin, set: (obj, value) => { obj.countryOfOrigin = value; } }, metadata: _metadata }, _countryOfOrigin_initializers, _countryOfOrigin_extraInitializers);
        __esDecorate(null, null, _hsnCode_decorators, { kind: "field", name: "hsnCode", static: false, private: false, access: { has: obj => "hsnCode" in obj, get: obj => obj.hsnCode, set: (obj, value) => { obj.hsnCode = value; } }, metadata: _metadata }, _hsnCode_initializers, _hsnCode_extraInitializers);
        __esDecorate(null, null, _condition_decorators, { kind: "field", name: "condition", static: false, private: false, access: { has: obj => "condition" in obj, get: obj => obj.condition, set: (obj, value) => { obj.condition = value; } }, metadata: _metadata }, _condition_initializers, _condition_extraInitializers);
        __esDecorate(null, null, _itemName_decorators, { kind: "field", name: "itemName", static: false, private: false, access: { has: obj => "itemName" in obj, get: obj => obj.itemName, set: (obj, value) => { obj.itemName = value; } }, metadata: _metadata }, _itemName_initializers, _itemName_extraInitializers);
        __esDecorate(null, null, _firstInvoiceDate_decorators, { kind: "field", name: "firstInvoiceDate", static: false, private: false, access: { has: obj => "firstInvoiceDate" in obj, get: obj => obj.firstInvoiceDate, set: (obj, value) => { obj.firstInvoiceDate = value; } }, metadata: _metadata }, _firstInvoiceDate_initializers, _firstInvoiceDate_extraInitializers);
        __esDecorate(null, null, _purchasePrice_decorators, { kind: "field", name: "purchasePrice", static: false, private: false, access: { has: obj => "purchasePrice" in obj, get: obj => obj.purchasePrice, set: (obj, value) => { obj.purchasePrice = value; } }, metadata: _metadata }, _purchasePrice_initializers, _purchasePrice_extraInitializers);
        __esDecorate(null, null, _wholesalePrice_decorators, { kind: "field", name: "wholesalePrice", static: false, private: false, access: { has: obj => "wholesalePrice" in obj, get: obj => obj.wholesalePrice, set: (obj, value) => { obj.wholesalePrice = value; } }, metadata: _metadata }, _wholesalePrice_initializers, _wholesalePrice_extraInitializers);
        __esDecorate(null, null, _boxPrice_decorators, { kind: "field", name: "boxPrice", static: false, private: false, access: { has: obj => "boxPrice" in obj, get: obj => obj.boxPrice, set: (obj, value) => { obj.boxPrice = value; } }, metadata: _metadata }, _boxPrice_initializers, _boxPrice_extraInitializers);
        __esDecorate(null, null, _taxRate_decorators, { kind: "field", name: "taxRate", static: false, private: false, access: { has: obj => "taxRate" in obj, get: obj => obj.taxRate, set: (obj, value) => { obj.taxRate = value; } }, metadata: _metadata }, _taxRate_initializers, _taxRate_extraInitializers);
        __esDecorate(null, null, _taxAmount_decorators, { kind: "field", name: "taxAmount", static: false, private: false, access: { has: obj => "taxAmount" in obj, get: obj => obj.taxAmount, set: (obj, value) => { obj.taxAmount = value; } }, metadata: _metadata }, _taxAmount_initializers, _taxAmount_extraInitializers);
        __esDecorate(null, null, _totalCost_decorators, { kind: "field", name: "totalCost", static: false, private: false, access: { has: obj => "totalCost" in obj, get: obj => obj.totalCost, set: (obj, value) => { obj.totalCost = value; } }, metadata: _metadata }, _totalCost_initializers, _totalCost_extraInitializers);
        __esDecorate(null, null, _sellingPrice_decorators, { kind: "field", name: "sellingPrice", static: false, private: false, access: { has: obj => "sellingPrice" in obj, get: obj => obj.sellingPrice, set: (obj, value) => { obj.sellingPrice = value; } }, metadata: _metadata }, _sellingPrice_initializers, _sellingPrice_extraInitializers);
        __esDecorate(null, null, _onlinePrice_decorators, { kind: "field", name: "onlinePrice", static: false, private: false, access: { has: obj => "onlinePrice" in obj, get: obj => obj.onlinePrice, set: (obj, value) => { obj.onlinePrice = value; } }, metadata: _metadata }, _onlinePrice_initializers, _onlinePrice_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _isOnline_decorators, { kind: "field", name: "isOnline", static: false, private: false, access: { has: obj => "isOnline" in obj, get: obj => obj.isOnline, set: (obj, value) => { obj.isOnline = value; } }, metadata: _metadata }, _isOnline_initializers, _isOnline_extraInitializers);
        __esDecorate(null, null, _birthdayOffer_decorators, { kind: "field", name: "birthdayOffer", static: false, private: false, access: { has: obj => "birthdayOffer" in obj, get: obj => obj.birthdayOffer, set: (obj, value) => { obj.birthdayOffer = value; } }, metadata: _metadata }, _birthdayOffer_initializers, _birthdayOffer_extraInitializers);
        __esDecorate(null, null, _branch_decorators, { kind: "field", name: "branch", static: false, private: false, access: { has: obj => "branch" in obj, get: obj => obj.branch, set: (obj, value) => { obj.branch = value; } }, metadata: _metadata }, _branch_initializers, _branch_extraInitializers);
        __esDecorate(null, null, _branchId_decorators, { kind: "field", name: "branchId", static: false, private: false, access: { has: obj => "branchId" in obj, get: obj => obj.branchId, set: (obj, value) => { obj.branchId = value; } }, metadata: _metadata }, _branchId_initializers, _branchId_extraInitializers);
        __esDecorate(null, null, _purchaseId_decorators, { kind: "field", name: "purchaseId", static: false, private: false, access: { has: obj => "purchaseId" in obj, get: obj => obj.purchaseId, set: (obj, value) => { obj.purchaseId = value; } }, metadata: _metadata }, _purchaseId_initializers, _purchaseId_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: obj => "notes" in obj, get: obj => obj.notes, set: (obj, value) => { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _accessories_decorators, { kind: "field", name: "accessories", static: false, private: false, access: { has: obj => "accessories" in obj, get: obj => obj.accessories, set: (obj, value) => { obj.accessories = value; } }, metadata: _metadata }, _accessories_initializers, _accessories_extraInitializers);
        __esDecorate(null, null, _images_decorators, { kind: "field", name: "images", static: false, private: false, access: { has: obj => "images" in obj, get: obj => obj.images, set: (obj, value) => { obj.images = value; } }, metadata: _metadata }, _images_initializers, _images_extraInitializers);
        __esDecorate(null, null, _warrantyStatus_decorators, { kind: "field", name: "warrantyStatus", static: false, private: false, access: { has: obj => "warrantyStatus" in obj, get: obj => obj.warrantyStatus, set: (obj, value) => { obj.warrantyStatus = value; } }, metadata: _metadata }, _warrantyStatus_initializers, _warrantyStatus_extraInitializers);
        __esDecorate(null, null, _warrantyExpiry_decorators, { kind: "field", name: "warrantyExpiry", static: false, private: false, access: { has: obj => "warrantyExpiry" in obj, get: obj => obj.warrantyExpiry, set: (obj, value) => { obj.warrantyExpiry = value; } }, metadata: _metadata }, _warrantyExpiry_initializers, _warrantyExpiry_extraInitializers);
        __esDecorate(null, null, _createdBy_decorators, { kind: "field", name: "createdBy", static: false, private: false, access: { has: obj => "createdBy" in obj, get: obj => obj.createdBy, set: (obj, value) => { obj.createdBy = value; } }, metadata: _metadata }, _createdBy_initializers, _createdBy_extraInitializers);
        __esDecorate(null, null, _createdById_decorators, { kind: "field", name: "createdById", static: false, private: false, access: { has: obj => "createdById" in obj, get: obj => obj.createdById, set: (obj, value) => { obj.createdById = value; } }, metadata: _metadata }, _createdById_initializers, _createdById_extraInitializers);
        __esDecorate(null, null, _photos_decorators, { kind: "field", name: "photos", static: false, private: false, access: { has: obj => "photos" in obj, get: obj => obj.photos, set: (obj, value) => { obj.photos = value; } }, metadata: _metadata }, _photos_initializers, _photos_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        InventoryItem = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return InventoryItem = _classThis;
})();
export { InventoryItem };
//# sourceMappingURL=inventory-item.entity.js.map