var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn, CreateDateColumn, UpdateDateColumn, } from 'typeorm';
import { User } from '../../auth/entities/user.entity';
let Banner = (() => {
    let _classDecorators = [Entity('content_banners')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _title_decorators;
    let _title_initializers = [];
    let _title_extraInitializers = [];
    let _subtitle_decorators;
    let _subtitle_initializers = [];
    let _subtitle_extraInitializers = [];
    let _imageUrl_decorators;
    let _imageUrl_initializers = [];
    let _imageUrl_extraInitializers = [];
    let _mobileImageUrl_decorators;
    let _mobileImageUrl_initializers = [];
    let _mobileImageUrl_extraInitializers = [];
    let _linkUrl_decorators;
    let _linkUrl_initializers = [];
    let _linkUrl_extraInitializers = [];
    let _ctaText_decorators;
    let _ctaText_initializers = [];
    let _ctaText_extraInitializers = [];
    let _pageType_decorators;
    let _pageType_initializers = [];
    let _pageType_extraInitializers = [];
    let _position_decorators;
    let _position_initializers = [];
    let _position_extraInitializers = [];
    let _deviceType_decorators;
    let _deviceType_initializers = [];
    let _deviceType_extraInitializers = [];
    let _sortOrder_decorators;
    let _sortOrder_initializers = [];
    let _sortOrder_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    let _clickCount_decorators;
    let _clickCount_initializers = [];
    let _clickCount_extraInitializers = [];
    let _startsAt_decorators;
    let _startsAt_initializers = [];
    let _startsAt_extraInitializers = [];
    let _endsAt_decorators;
    let _endsAt_initializers = [];
    let _endsAt_extraInitializers = [];
    let _createdById_decorators;
    let _createdById_initializers = [];
    let _createdById_extraInitializers = [];
    let _createdBy_decorators;
    let _createdBy_initializers = [];
    let _createdBy_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var Banner = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.title = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _title_initializers, void 0));
            this.subtitle = (__runInitializers(this, _title_extraInitializers), __runInitializers(this, _subtitle_initializers, void 0));
            this.imageUrl = (__runInitializers(this, _subtitle_extraInitializers), __runInitializers(this, _imageUrl_initializers, void 0));
            this.mobileImageUrl = (__runInitializers(this, _imageUrl_extraInitializers), __runInitializers(this, _mobileImageUrl_initializers, void 0));
            this.linkUrl = (__runInitializers(this, _mobileImageUrl_extraInitializers), __runInitializers(this, _linkUrl_initializers, void 0));
            this.ctaText = (__runInitializers(this, _linkUrl_extraInitializers), __runInitializers(this, _ctaText_initializers, void 0));
            this.pageType = (__runInitializers(this, _ctaText_extraInitializers), __runInitializers(this, _pageType_initializers, void 0));
            this.position = (__runInitializers(this, _pageType_extraInitializers), __runInitializers(this, _position_initializers, void 0));
            this.deviceType = (__runInitializers(this, _position_extraInitializers), __runInitializers(this, _deviceType_initializers, void 0));
            this.sortOrder = (__runInitializers(this, _deviceType_extraInitializers), __runInitializers(this, _sortOrder_initializers, void 0));
            this.isActive = (__runInitializers(this, _sortOrder_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.clickCount = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _clickCount_initializers, void 0));
            this.startsAt = (__runInitializers(this, _clickCount_extraInitializers), __runInitializers(this, _startsAt_initializers, void 0));
            this.endsAt = (__runInitializers(this, _startsAt_extraInitializers), __runInitializers(this, _endsAt_initializers, void 0));
            this.createdById = (__runInitializers(this, _endsAt_extraInitializers), __runInitializers(this, _createdById_initializers, void 0));
            this.createdBy = (__runInitializers(this, _createdById_extraInitializers), __runInitializers(this, _createdBy_initializers, void 0));
            this.createdAt = (__runInitializers(this, _createdBy_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "Banner");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _title_decorators = [Column()];
        _subtitle_decorators = [Column({ nullable: true, type: 'varchar' })];
        _imageUrl_decorators = [Column({ name: 'image_url' })];
        _mobileImageUrl_decorators = [Column({ name: 'mobile_image_url', nullable: true, type: 'varchar' })];
        _linkUrl_decorators = [Column({ name: 'link_url', nullable: true, type: 'varchar' })];
        _ctaText_decorators = [Column({ name: 'cta_text', nullable: true, type: 'varchar' })];
        _pageType_decorators = [Column({ name: 'page_type', default: 'home', type: 'varchar' })];
        _position_decorators = [Column({ name: 'position', default: 'slider', type: 'varchar' })];
        _deviceType_decorators = [Column({ name: 'device_type', default: 'all', type: 'varchar' })];
        _sortOrder_decorators = [Column({ name: 'sort_order', default: 0 })];
        _isActive_decorators = [Column({ name: 'is_active', default: true })];
        _clickCount_decorators = [Column({ name: 'click_count', default: 0 })];
        _startsAt_decorators = [Column({ name: 'starts_at', nullable: true, type: 'timestamptz' })];
        _endsAt_decorators = [Column({ name: 'ends_at', nullable: true, type: 'timestamptz' })];
        _createdById_decorators = [Column({ name: 'created_by', nullable: true, type: 'varchar' })];
        _createdBy_decorators = [ManyToOne(() => User, { eager: false, nullable: true }), JoinColumn({ name: 'created_by' })];
        _createdAt_decorators = [CreateDateColumn({ name: 'created_at' })];
        _updatedAt_decorators = [UpdateDateColumn({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _title_decorators, { kind: "field", name: "title", static: false, private: false, access: { has: obj => "title" in obj, get: obj => obj.title, set: (obj, value) => { obj.title = value; } }, metadata: _metadata }, _title_initializers, _title_extraInitializers);
        __esDecorate(null, null, _subtitle_decorators, { kind: "field", name: "subtitle", static: false, private: false, access: { has: obj => "subtitle" in obj, get: obj => obj.subtitle, set: (obj, value) => { obj.subtitle = value; } }, metadata: _metadata }, _subtitle_initializers, _subtitle_extraInitializers);
        __esDecorate(null, null, _imageUrl_decorators, { kind: "field", name: "imageUrl", static: false, private: false, access: { has: obj => "imageUrl" in obj, get: obj => obj.imageUrl, set: (obj, value) => { obj.imageUrl = value; } }, metadata: _metadata }, _imageUrl_initializers, _imageUrl_extraInitializers);
        __esDecorate(null, null, _mobileImageUrl_decorators, { kind: "field", name: "mobileImageUrl", static: false, private: false, access: { has: obj => "mobileImageUrl" in obj, get: obj => obj.mobileImageUrl, set: (obj, value) => { obj.mobileImageUrl = value; } }, metadata: _metadata }, _mobileImageUrl_initializers, _mobileImageUrl_extraInitializers);
        __esDecorate(null, null, _linkUrl_decorators, { kind: "field", name: "linkUrl", static: false, private: false, access: { has: obj => "linkUrl" in obj, get: obj => obj.linkUrl, set: (obj, value) => { obj.linkUrl = value; } }, metadata: _metadata }, _linkUrl_initializers, _linkUrl_extraInitializers);
        __esDecorate(null, null, _ctaText_decorators, { kind: "field", name: "ctaText", static: false, private: false, access: { has: obj => "ctaText" in obj, get: obj => obj.ctaText, set: (obj, value) => { obj.ctaText = value; } }, metadata: _metadata }, _ctaText_initializers, _ctaText_extraInitializers);
        __esDecorate(null, null, _pageType_decorators, { kind: "field", name: "pageType", static: false, private: false, access: { has: obj => "pageType" in obj, get: obj => obj.pageType, set: (obj, value) => { obj.pageType = value; } }, metadata: _metadata }, _pageType_initializers, _pageType_extraInitializers);
        __esDecorate(null, null, _position_decorators, { kind: "field", name: "position", static: false, private: false, access: { has: obj => "position" in obj, get: obj => obj.position, set: (obj, value) => { obj.position = value; } }, metadata: _metadata }, _position_initializers, _position_extraInitializers);
        __esDecorate(null, null, _deviceType_decorators, { kind: "field", name: "deviceType", static: false, private: false, access: { has: obj => "deviceType" in obj, get: obj => obj.deviceType, set: (obj, value) => { obj.deviceType = value; } }, metadata: _metadata }, _deviceType_initializers, _deviceType_extraInitializers);
        __esDecorate(null, null, _sortOrder_decorators, { kind: "field", name: "sortOrder", static: false, private: false, access: { has: obj => "sortOrder" in obj, get: obj => obj.sortOrder, set: (obj, value) => { obj.sortOrder = value; } }, metadata: _metadata }, _sortOrder_initializers, _sortOrder_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _clickCount_decorators, { kind: "field", name: "clickCount", static: false, private: false, access: { has: obj => "clickCount" in obj, get: obj => obj.clickCount, set: (obj, value) => { obj.clickCount = value; } }, metadata: _metadata }, _clickCount_initializers, _clickCount_extraInitializers);
        __esDecorate(null, null, _startsAt_decorators, { kind: "field", name: "startsAt", static: false, private: false, access: { has: obj => "startsAt" in obj, get: obj => obj.startsAt, set: (obj, value) => { obj.startsAt = value; } }, metadata: _metadata }, _startsAt_initializers, _startsAt_extraInitializers);
        __esDecorate(null, null, _endsAt_decorators, { kind: "field", name: "endsAt", static: false, private: false, access: { has: obj => "endsAt" in obj, get: obj => obj.endsAt, set: (obj, value) => { obj.endsAt = value; } }, metadata: _metadata }, _endsAt_initializers, _endsAt_extraInitializers);
        __esDecorate(null, null, _createdById_decorators, { kind: "field", name: "createdById", static: false, private: false, access: { has: obj => "createdById" in obj, get: obj => obj.createdById, set: (obj, value) => { obj.createdById = value; } }, metadata: _metadata }, _createdById_initializers, _createdById_extraInitializers);
        __esDecorate(null, null, _createdBy_decorators, { kind: "field", name: "createdBy", static: false, private: false, access: { has: obj => "createdBy" in obj, get: obj => obj.createdBy, set: (obj, value) => { obj.createdBy = value; } }, metadata: _metadata }, _createdBy_initializers, _createdBy_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Banner = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Banner = _classThis;
})();
export { Banner };
let ContentPage = (() => {
    let _classDecorators = [Entity('content_pages')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _slug_decorators;
    let _slug_initializers = [];
    let _slug_extraInitializers = [];
    let _title_decorators;
    let _title_initializers = [];
    let _title_extraInitializers = [];
    let _content_decorators;
    let _content_initializers = [];
    let _content_extraInitializers = [];
    let _metaTitle_decorators;
    let _metaTitle_initializers = [];
    let _metaTitle_extraInitializers = [];
    let _metaDesc_decorators;
    let _metaDesc_initializers = [];
    let _metaDesc_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    let _updatedById_decorators;
    let _updatedById_initializers = [];
    let _updatedById_extraInitializers = [];
    let _updatedBy_decorators;
    let _updatedBy_initializers = [];
    let _updatedBy_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var ContentPage = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.slug = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _slug_initializers, void 0));
            this.title = (__runInitializers(this, _slug_extraInitializers), __runInitializers(this, _title_initializers, void 0));
            this.content = (__runInitializers(this, _title_extraInitializers), __runInitializers(this, _content_initializers, void 0));
            this.metaTitle = (__runInitializers(this, _content_extraInitializers), __runInitializers(this, _metaTitle_initializers, void 0));
            this.metaDesc = (__runInitializers(this, _metaTitle_extraInitializers), __runInitializers(this, _metaDesc_initializers, void 0));
            this.isActive = (__runInitializers(this, _metaDesc_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.updatedById = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _updatedById_initializers, void 0));
            this.updatedBy = (__runInitializers(this, _updatedById_extraInitializers), __runInitializers(this, _updatedBy_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _updatedBy_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "ContentPage");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [PrimaryGeneratedColumn('uuid')];
        _slug_decorators = [Column({ unique: true })];
        _title_decorators = [Column()];
        _content_decorators = [Column({ nullable: true, type: 'text' })];
        _metaTitle_decorators = [Column({ name: 'meta_title', nullable: true, type: 'varchar' })];
        _metaDesc_decorators = [Column({ name: 'meta_desc', nullable: true, type: 'varchar' })];
        _isActive_decorators = [Column({ name: 'is_active', default: true })];
        _updatedById_decorators = [Column({ name: 'updated_by', nullable: true, type: 'varchar' })];
        _updatedBy_decorators = [ManyToOne(() => User, { eager: false, nullable: true }), JoinColumn({ name: 'updated_by' })];
        _updatedAt_decorators = [UpdateDateColumn({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _slug_decorators, { kind: "field", name: "slug", static: false, private: false, access: { has: obj => "slug" in obj, get: obj => obj.slug, set: (obj, value) => { obj.slug = value; } }, metadata: _metadata }, _slug_initializers, _slug_extraInitializers);
        __esDecorate(null, null, _title_decorators, { kind: "field", name: "title", static: false, private: false, access: { has: obj => "title" in obj, get: obj => obj.title, set: (obj, value) => { obj.title = value; } }, metadata: _metadata }, _title_initializers, _title_extraInitializers);
        __esDecorate(null, null, _content_decorators, { kind: "field", name: "content", static: false, private: false, access: { has: obj => "content" in obj, get: obj => obj.content, set: (obj, value) => { obj.content = value; } }, metadata: _metadata }, _content_initializers, _content_extraInitializers);
        __esDecorate(null, null, _metaTitle_decorators, { kind: "field", name: "metaTitle", static: false, private: false, access: { has: obj => "metaTitle" in obj, get: obj => obj.metaTitle, set: (obj, value) => { obj.metaTitle = value; } }, metadata: _metadata }, _metaTitle_initializers, _metaTitle_extraInitializers);
        __esDecorate(null, null, _metaDesc_decorators, { kind: "field", name: "metaDesc", static: false, private: false, access: { has: obj => "metaDesc" in obj, get: obj => obj.metaDesc, set: (obj, value) => { obj.metaDesc = value; } }, metadata: _metadata }, _metaDesc_initializers, _metaDesc_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _updatedById_decorators, { kind: "field", name: "updatedById", static: false, private: false, access: { has: obj => "updatedById" in obj, get: obj => obj.updatedById, set: (obj, value) => { obj.updatedById = value; } }, metadata: _metadata }, _updatedById_initializers, _updatedById_extraInitializers);
        __esDecorate(null, null, _updatedBy_decorators, { kind: "field", name: "updatedBy", static: false, private: false, access: { has: obj => "updatedBy" in obj, get: obj => obj.updatedBy, set: (obj, value) => { obj.updatedBy = value; } }, metadata: _metadata }, _updatedBy_initializers, _updatedBy_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        ContentPage = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return ContentPage = _classThis;
})();
export { ContentPage };
//# sourceMappingURL=banner.entity.js.map