var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
import { IsString, IsNotEmpty, IsOptional, IsNumber, IsBoolean, IsDateString, Min, Max, IsUUID, } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
let CreateInventoryItemDto = (() => {
    var _a;
    let _imei_decorators;
    let _imei_initializers = [];
    let _imei_extraInitializers = [];
    let _imei2_decorators;
    let _imei2_initializers = [];
    let _imei2_extraInitializers = [];
    let _brandId_decorators;
    let _brandId_initializers = [];
    let _brandId_extraInitializers = [];
    let _modelId_decorators;
    let _modelId_initializers = [];
    let _modelId_extraInitializers = [];
    let _colour_decorators;
    let _colour_initializers = [];
    let _colour_extraInitializers = [];
    let _storage_decorators;
    let _storage_initializers = [];
    let _storage_extraInitializers = [];
    let _ram_decorators;
    let _ram_initializers = [];
    let _ram_extraInitializers = [];
    let _boxType_decorators;
    let _boxType_initializers = [];
    let _boxType_extraInitializers = [];
    let _pkuCode_decorators;
    let _pkuCode_initializers = [];
    let _pkuCode_extraInitializers = [];
    let _batteryHealth_decorators;
    let _batteryHealth_initializers = [];
    let _batteryHealth_extraInitializers = [];
    let _countryOfOrigin_decorators;
    let _countryOfOrigin_initializers = [];
    let _countryOfOrigin_extraInitializers = [];
    let _hsnCode_decorators;
    let _hsnCode_initializers = [];
    let _hsnCode_extraInitializers = [];
    let _condition_decorators;
    let _condition_initializers = [];
    let _condition_extraInitializers = [];
    let _itemName_decorators;
    let _itemName_initializers = [];
    let _itemName_extraInitializers = [];
    let _firstInvoiceDate_decorators;
    let _firstInvoiceDate_initializers = [];
    let _firstInvoiceDate_extraInitializers = [];
    let _purchasePrice_decorators;
    let _purchasePrice_initializers = [];
    let _purchasePrice_extraInitializers = [];
    let _wholesalePrice_decorators;
    let _wholesalePrice_initializers = [];
    let _wholesalePrice_extraInitializers = [];
    let _boxPrice_decorators;
    let _boxPrice_initializers = [];
    let _boxPrice_extraInitializers = [];
    let _taxRate_decorators;
    let _taxRate_initializers = [];
    let _taxRate_extraInitializers = [];
    let _taxAmount_decorators;
    let _taxAmount_initializers = [];
    let _taxAmount_extraInitializers = [];
    let _sellingPrice_decorators;
    let _sellingPrice_initializers = [];
    let _sellingPrice_extraInitializers = [];
    let _onlinePrice_decorators;
    let _onlinePrice_initializers = [];
    let _onlinePrice_extraInitializers = [];
    let _branchId_decorators;
    let _branchId_initializers = [];
    let _branchId_extraInitializers = [];
    let _notes_decorators;
    let _notes_initializers = [];
    let _notes_extraInitializers = [];
    let _accessories_decorators;
    let _accessories_initializers = [];
    let _accessories_extraInitializers = [];
    let _warrantyStatus_decorators;
    let _warrantyStatus_initializers = [];
    let _warrantyStatus_extraInitializers = [];
    let _birthdayOffer_decorators;
    let _birthdayOffer_initializers = [];
    let _birthdayOffer_extraInitializers = [];
    return _a = class CreateInventoryItemDto {
            constructor() {
                this.imei = __runInitializers(this, _imei_initializers, void 0);
                this.imei2 = (__runInitializers(this, _imei_extraInitializers), __runInitializers(this, _imei2_initializers, void 0));
                this.brandId = (__runInitializers(this, _imei2_extraInitializers), __runInitializers(this, _brandId_initializers, void 0));
                this.modelId = (__runInitializers(this, _brandId_extraInitializers), __runInitializers(this, _modelId_initializers, void 0));
                this.colour = (__runInitializers(this, _modelId_extraInitializers), __runInitializers(this, _colour_initializers, void 0));
                this.storage = (__runInitializers(this, _colour_extraInitializers), __runInitializers(this, _storage_initializers, void 0));
                this.ram = (__runInitializers(this, _storage_extraInitializers), __runInitializers(this, _ram_initializers, void 0));
                this.boxType = (__runInitializers(this, _ram_extraInitializers), __runInitializers(this, _boxType_initializers, void 0));
                this.pkuCode = (__runInitializers(this, _boxType_extraInitializers), __runInitializers(this, _pkuCode_initializers, void 0));
                this.batteryHealth = (__runInitializers(this, _pkuCode_extraInitializers), __runInitializers(this, _batteryHealth_initializers, void 0));
                this.countryOfOrigin = (__runInitializers(this, _batteryHealth_extraInitializers), __runInitializers(this, _countryOfOrigin_initializers, void 0));
                this.hsnCode = (__runInitializers(this, _countryOfOrigin_extraInitializers), __runInitializers(this, _hsnCode_initializers, void 0));
                this.condition = (__runInitializers(this, _hsnCode_extraInitializers), __runInitializers(this, _condition_initializers, void 0));
                this.itemName = (__runInitializers(this, _condition_extraInitializers), __runInitializers(this, _itemName_initializers, void 0));
                this.firstInvoiceDate = (__runInitializers(this, _itemName_extraInitializers), __runInitializers(this, _firstInvoiceDate_initializers, void 0));
                this.purchasePrice = (__runInitializers(this, _firstInvoiceDate_extraInitializers), __runInitializers(this, _purchasePrice_initializers, void 0));
                this.wholesalePrice = (__runInitializers(this, _purchasePrice_extraInitializers), __runInitializers(this, _wholesalePrice_initializers, void 0));
                this.boxPrice = (__runInitializers(this, _wholesalePrice_extraInitializers), __runInitializers(this, _boxPrice_initializers, void 0));
                this.taxRate = (__runInitializers(this, _boxPrice_extraInitializers), __runInitializers(this, _taxRate_initializers, void 0));
                this.taxAmount = (__runInitializers(this, _taxRate_extraInitializers), __runInitializers(this, _taxAmount_initializers, void 0));
                this.sellingPrice = (__runInitializers(this, _taxAmount_extraInitializers), __runInitializers(this, _sellingPrice_initializers, void 0));
                this.onlinePrice = (__runInitializers(this, _sellingPrice_extraInitializers), __runInitializers(this, _onlinePrice_initializers, void 0));
                this.branchId = (__runInitializers(this, _onlinePrice_extraInitializers), __runInitializers(this, _branchId_initializers, void 0));
                this.notes = (__runInitializers(this, _branchId_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
                this.accessories = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _accessories_initializers, void 0));
                this.warrantyStatus = (__runInitializers(this, _accessories_extraInitializers), __runInitializers(this, _warrantyStatus_initializers, void 0));
                this.birthdayOffer = (__runInitializers(this, _warrantyStatus_extraInitializers), __runInitializers(this, _birthdayOffer_initializers, void 0));
                __runInitializers(this, _birthdayOffer_extraInitializers);
            }
        },
        (() => {
            const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _imei_decorators = [ApiProperty({ description: '15-digit IMEI number' }), IsString(), IsNotEmpty()];
            _imei2_decorators = [ApiPropertyOptional({ description: 'Secondary IMEI for dual-SIM devices' }), IsOptional(), IsString()];
            _brandId_decorators = [ApiProperty(), IsUUID()];
            _modelId_decorators = [ApiProperty(), IsUUID()];
            _colour_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _storage_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _ram_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _boxType_decorators = [ApiProperty({ description: 'with_box | without_box | accessories_only' }), IsString(), IsNotEmpty()];
            _pkuCode_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _batteryHealth_decorators = [ApiPropertyOptional({ minimum: 0, maximum: 100 }), IsOptional(), IsNumber(), Min(0), Max(100), Type(() => Number)];
            _countryOfOrigin_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _hsnCode_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _condition_decorators = [ApiProperty({ description: 'sealed_pack | open_box | super_mint | mint | good' }), IsString(), IsNotEmpty()];
            _itemName_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _firstInvoiceDate_decorators = [ApiPropertyOptional(), IsOptional(), IsDateString()];
            _purchasePrice_decorators = [ApiProperty(), IsNumber(), Min(0), Type(() => Number)];
            _wholesalePrice_decorators = [ApiPropertyOptional(), IsOptional(), IsNumber(), Min(0), Type(() => Number)];
            _boxPrice_decorators = [ApiPropertyOptional(), IsOptional(), IsNumber(), Min(0), Type(() => Number)];
            _taxRate_decorators = [ApiPropertyOptional({ default: 0 }), IsOptional(), IsNumber(), Min(0), Type(() => Number)];
            _taxAmount_decorators = [ApiPropertyOptional({ default: 0 }), IsOptional(), IsNumber(), Min(0), Type(() => Number)];
            _sellingPrice_decorators = [ApiPropertyOptional(), IsOptional(), IsNumber(), Min(0), Type(() => Number)];
            _onlinePrice_decorators = [ApiPropertyOptional(), IsOptional(), IsNumber(), Min(0), Type(() => Number)];
            _branchId_decorators = [ApiProperty(), IsUUID()];
            _notes_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _accessories_decorators = [ApiPropertyOptional(), IsOptional()];
            _warrantyStatus_decorators = [ApiPropertyOptional(), IsOptional(), IsString()];
            _birthdayOffer_decorators = [ApiPropertyOptional(), IsOptional(), IsBoolean()];
            __esDecorate(null, null, _imei_decorators, { kind: "field", name: "imei", static: false, private: false, access: { has: obj => "imei" in obj, get: obj => obj.imei, set: (obj, value) => { obj.imei = value; } }, metadata: _metadata }, _imei_initializers, _imei_extraInitializers);
            __esDecorate(null, null, _imei2_decorators, { kind: "field", name: "imei2", static: false, private: false, access: { has: obj => "imei2" in obj, get: obj => obj.imei2, set: (obj, value) => { obj.imei2 = value; } }, metadata: _metadata }, _imei2_initializers, _imei2_extraInitializers);
            __esDecorate(null, null, _brandId_decorators, { kind: "field", name: "brandId", static: false, private: false, access: { has: obj => "brandId" in obj, get: obj => obj.brandId, set: (obj, value) => { obj.brandId = value; } }, metadata: _metadata }, _brandId_initializers, _brandId_extraInitializers);
            __esDecorate(null, null, _modelId_decorators, { kind: "field", name: "modelId", static: false, private: false, access: { has: obj => "modelId" in obj, get: obj => obj.modelId, set: (obj, value) => { obj.modelId = value; } }, metadata: _metadata }, _modelId_initializers, _modelId_extraInitializers);
            __esDecorate(null, null, _colour_decorators, { kind: "field", name: "colour", static: false, private: false, access: { has: obj => "colour" in obj, get: obj => obj.colour, set: (obj, value) => { obj.colour = value; } }, metadata: _metadata }, _colour_initializers, _colour_extraInitializers);
            __esDecorate(null, null, _storage_decorators, { kind: "field", name: "storage", static: false, private: false, access: { has: obj => "storage" in obj, get: obj => obj.storage, set: (obj, value) => { obj.storage = value; } }, metadata: _metadata }, _storage_initializers, _storage_extraInitializers);
            __esDecorate(null, null, _ram_decorators, { kind: "field", name: "ram", static: false, private: false, access: { has: obj => "ram" in obj, get: obj => obj.ram, set: (obj, value) => { obj.ram = value; } }, metadata: _metadata }, _ram_initializers, _ram_extraInitializers);
            __esDecorate(null, null, _boxType_decorators, { kind: "field", name: "boxType", static: false, private: false, access: { has: obj => "boxType" in obj, get: obj => obj.boxType, set: (obj, value) => { obj.boxType = value; } }, metadata: _metadata }, _boxType_initializers, _boxType_extraInitializers);
            __esDecorate(null, null, _pkuCode_decorators, { kind: "field", name: "pkuCode", static: false, private: false, access: { has: obj => "pkuCode" in obj, get: obj => obj.pkuCode, set: (obj, value) => { obj.pkuCode = value; } }, metadata: _metadata }, _pkuCode_initializers, _pkuCode_extraInitializers);
            __esDecorate(null, null, _batteryHealth_decorators, { kind: "field", name: "batteryHealth", static: false, private: false, access: { has: obj => "batteryHealth" in obj, get: obj => obj.batteryHealth, set: (obj, value) => { obj.batteryHealth = value; } }, metadata: _metadata }, _batteryHealth_initializers, _batteryHealth_extraInitializers);
            __esDecorate(null, null, _countryOfOrigin_decorators, { kind: "field", name: "countryOfOrigin", static: false, private: false, access: { has: obj => "countryOfOrigin" in obj, get: obj => obj.countryOfOrigin, set: (obj, value) => { obj.countryOfOrigin = value; } }, metadata: _metadata }, _countryOfOrigin_initializers, _countryOfOrigin_extraInitializers);
            __esDecorate(null, null, _hsnCode_decorators, { kind: "field", name: "hsnCode", static: false, private: false, access: { has: obj => "hsnCode" in obj, get: obj => obj.hsnCode, set: (obj, value) => { obj.hsnCode = value; } }, metadata: _metadata }, _hsnCode_initializers, _hsnCode_extraInitializers);
            __esDecorate(null, null, _condition_decorators, { kind: "field", name: "condition", static: false, private: false, access: { has: obj => "condition" in obj, get: obj => obj.condition, set: (obj, value) => { obj.condition = value; } }, metadata: _metadata }, _condition_initializers, _condition_extraInitializers);
            __esDecorate(null, null, _itemName_decorators, { kind: "field", name: "itemName", static: false, private: false, access: { has: obj => "itemName" in obj, get: obj => obj.itemName, set: (obj, value) => { obj.itemName = value; } }, metadata: _metadata }, _itemName_initializers, _itemName_extraInitializers);
            __esDecorate(null, null, _firstInvoiceDate_decorators, { kind: "field", name: "firstInvoiceDate", static: false, private: false, access: { has: obj => "firstInvoiceDate" in obj, get: obj => obj.firstInvoiceDate, set: (obj, value) => { obj.firstInvoiceDate = value; } }, metadata: _metadata }, _firstInvoiceDate_initializers, _firstInvoiceDate_extraInitializers);
            __esDecorate(null, null, _purchasePrice_decorators, { kind: "field", name: "purchasePrice", static: false, private: false, access: { has: obj => "purchasePrice" in obj, get: obj => obj.purchasePrice, set: (obj, value) => { obj.purchasePrice = value; } }, metadata: _metadata }, _purchasePrice_initializers, _purchasePrice_extraInitializers);
            __esDecorate(null, null, _wholesalePrice_decorators, { kind: "field", name: "wholesalePrice", static: false, private: false, access: { has: obj => "wholesalePrice" in obj, get: obj => obj.wholesalePrice, set: (obj, value) => { obj.wholesalePrice = value; } }, metadata: _metadata }, _wholesalePrice_initializers, _wholesalePrice_extraInitializers);
            __esDecorate(null, null, _boxPrice_decorators, { kind: "field", name: "boxPrice", static: false, private: false, access: { has: obj => "boxPrice" in obj, get: obj => obj.boxPrice, set: (obj, value) => { obj.boxPrice = value; } }, metadata: _metadata }, _boxPrice_initializers, _boxPrice_extraInitializers);
            __esDecorate(null, null, _taxRate_decorators, { kind: "field", name: "taxRate", static: false, private: false, access: { has: obj => "taxRate" in obj, get: obj => obj.taxRate, set: (obj, value) => { obj.taxRate = value; } }, metadata: _metadata }, _taxRate_initializers, _taxRate_extraInitializers);
            __esDecorate(null, null, _taxAmount_decorators, { kind: "field", name: "taxAmount", static: false, private: false, access: { has: obj => "taxAmount" in obj, get: obj => obj.taxAmount, set: (obj, value) => { obj.taxAmount = value; } }, metadata: _metadata }, _taxAmount_initializers, _taxAmount_extraInitializers);
            __esDecorate(null, null, _sellingPrice_decorators, { kind: "field", name: "sellingPrice", static: false, private: false, access: { has: obj => "sellingPrice" in obj, get: obj => obj.sellingPrice, set: (obj, value) => { obj.sellingPrice = value; } }, metadata: _metadata }, _sellingPrice_initializers, _sellingPrice_extraInitializers);
            __esDecorate(null, null, _onlinePrice_decorators, { kind: "field", name: "onlinePrice", static: false, private: false, access: { has: obj => "onlinePrice" in obj, get: obj => obj.onlinePrice, set: (obj, value) => { obj.onlinePrice = value; } }, metadata: _metadata }, _onlinePrice_initializers, _onlinePrice_extraInitializers);
            __esDecorate(null, null, _branchId_decorators, { kind: "field", name: "branchId", static: false, private: false, access: { has: obj => "branchId" in obj, get: obj => obj.branchId, set: (obj, value) => { obj.branchId = value; } }, metadata: _metadata }, _branchId_initializers, _branchId_extraInitializers);
            __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: obj => "notes" in obj, get: obj => obj.notes, set: (obj, value) => { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
            __esDecorate(null, null, _accessories_decorators, { kind: "field", name: "accessories", static: false, private: false, access: { has: obj => "accessories" in obj, get: obj => obj.accessories, set: (obj, value) => { obj.accessories = value; } }, metadata: _metadata }, _accessories_initializers, _accessories_extraInitializers);
            __esDecorate(null, null, _warrantyStatus_decorators, { kind: "field", name: "warrantyStatus", static: false, private: false, access: { has: obj => "warrantyStatus" in obj, get: obj => obj.warrantyStatus, set: (obj, value) => { obj.warrantyStatus = value; } }, metadata: _metadata }, _warrantyStatus_initializers, _warrantyStatus_extraInitializers);
            __esDecorate(null, null, _birthdayOffer_decorators, { kind: "field", name: "birthdayOffer", static: false, private: false, access: { has: obj => "birthdayOffer" in obj, get: obj => obj.birthdayOffer, set: (obj, value) => { obj.birthdayOffer = value; } }, metadata: _metadata }, _birthdayOffer_initializers, _birthdayOffer_extraInitializers);
            if (_metadata) Object.defineProperty(_a, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        })(),
        _a;
})();
export { CreateInventoryItemDto };
//# sourceMappingURL=create-inventory-item.dto.js.map